COLS = {
    "roles": [("id", "PK vai trò."), ("name", "Tên vai trò (Owner, Staff, Admin)."), ("permissions", "JSONB quyền menu/thao tác."), ("created_at", "Thời điểm tạo bản ghi.")],
    "categories": [("id", "PK danh mục."), ("category_code", "Mã danh mục duy nhất."), ("name", "Tên hiển thị."), ("description", "Mô tả chi tiết danh mục."), ("parent_id", "FK danh mục cha (cây phân cấp)."), ("sort_order", "Thứ tự hiển thị."), ("status", "Active/Inactive."), ("created_at", "Tạo."), ("updated_at", "Cập nhật cuối.")],
    "suppliers": [("id", "PK nhà cung cấp."), ("supplier_code", "Mã NCC duy nhất."), ("name", "Tên NCC."), ("contact_person", "Người liên hệ."), ("phone", "SĐT."), ("email", "Email."), ("address", "Địa chỉ."), ("tax_code", "Mã số thuế."), ("status", "Active/Inactive."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "customers": [("id", "PK khách hàng."), ("customer_code", "Mã KH duy nhất."), ("name", "Tên khách / tổ chức."), ("phone", "SĐT bắt buộc."), ("email", "Email."), ("address", "Địa chỉ."), ("loyalty_points", "Điểm tích lũy."), ("status", "Active/Inactive."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "warehouselocations": [("id", "PK vị trí kho."), ("warehouse_code", "Mã kho."), ("shelf_code", "Mã kệ/vị trí."), ("description", "Mô tả vị trí."), ("capacity", "Sức chứa ước tính."), ("status", "Active/Maintenance/Inactive."), ("created_at", "Tạo.")],
    "users": [("id", "PK người dùng."), ("username", "Đăng nhập duy nhất."), ("password_hash", "Bcrypt/argon2 hash."), ("full_name", "Họ tên hiển thị."), ("email", "Email duy nhất."), ("phone", "SĐT."), ("role_id", "FK roles."), ("status", "Active/Locked."), ("last_login", "Đăng nhập gần nhất."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "products": [("id", "PK sản phẩm."), ("category_id", "FK categories."), ("sku_code", "Mã SKU duy nhất."), ("barcode", "Mã vạch."), ("name", "Tên sản phẩm."), ("image_url", "URL ảnh đại diện."), ("description", "Mô tả dài."), ("weight", "Khối lượng gram."), ("status", "Active/Inactive."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "productimages": [("id", "PK ảnh."), ("product_id", "FK products."), ("image_url", "URL ảnh."), ("alt_text", "Alt SEO."), ("is_primary", "Ảnh chính."), ("sort_order", "Thứ tự carousel."), ("file_size_bytes", "Kích thước file."), ("mime_type", "MIME."), ("created_at", "Tạo.")],
    "alertsettings": [("id", "PK cảnh báo."), ("owner_id", "FK users chủ cấu hình."), ("alert_type", "Loại: LowStock, ExpiryDate, ..."), ("threshold_value", "Ngưỡng kích hoạt."), ("channel", "App/Email/SMS/Zalo."), ("frequency", "Realtime/Daily/Weekly."), ("is_enabled", "Bật/tắt."), ("recipients", "JSON người nhận thêm."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "systemlogs": [("id", "PK log."), ("log_level", "INFO/WARNING/ERROR/CRITICAL."), ("module", "Module nguồn."), ("action", "Hành động."), ("user_id", "FK users (nullable)."), ("message", "Nội dung log."), ("stack_trace", "Stack khi lỗi."), ("context_data", "JSON bổ sung."), ("created_at", "Thời điểm ghi.")],
    "financeledger": [("id", "PK bút toán."), ("transaction_date", "Ngày chứng từ."), ("transaction_type", "Doanh thu/Chi phí/..."), ("reference_type", "Loại chứng từ nguồn."), ("reference_id", "ID chứng từ nguồn."), ("amount", "Dương thu âm chi."), ("description", "Diễn giải."), ("created_by", "FK users lập."), ("created_at", "Tạo."), ("updated_at", "Cập nhật."), ("fund_id", "FK cash_funds (đa quỹ).")],
    "aiinsights": [("id", "PK insight."), ("owner_id", "FK users."), ("dashboard_snapshot", "JSON snapshot dashboard."), ("prompt", "Prompt gửi LLM."), ("ai_advice", "Kết quả markdown."), ("model_used", "Tên model."), ("tokens_used", "Token tiêu thụ."), ("created_at", "Tạo.")],
    "aichathistory": [("id", "PK tin nhắn."), ("user_id", "FK users."), ("session_id", "Phiên chat."), ("message", "Nội dung."), ("sender", "User/Bot."), ("intent", "JSON intent nhận dạng."), ("response_time_ms", "Độ trễ phản hồi."), ("created_at", "Tạo.")],
    "mediaaudits": [("id", "PK audit media."), ("file_type", "OCR_Image/Voice_Audio."), ("cloud_url", "URL cloud."), ("entity_type", "Loại thực thể."), ("entity_id", "ID thực thể."), ("file_size_bytes", "Kích thước."), ("mime_type", "MIME."), ("uploaded_by", "FK users."), ("created_at", "Tạo.")],
    "productunits": [("id", "PK đơn vị."), ("product_id", "FK products."), ("unit_name", "Tên đơn vị (Thùng, Lon)."), ("conversion_rate", "Quy đổi về base unit."), ("is_base_unit", "Đơn vị cơ sở duy nhất."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "productpricehistory": [("id", "PK lịch sử giá."), ("product_id", "FK products."), ("unit_id", "FK productunits."), ("cost_price", "Giá vốn."), ("sale_price", "Giá bán."), ("effective_date", "Ngày hiệu lực."), ("created_at", "Tạo.")],
    "inventory": [("id", "PK tồn lô."), ("product_id", "FK products."), ("location_id", "FK warehouselocations."), ("batch_number", "Số lô."), ("expiry_date", "Hạn dùng."), ("quantity", "SL tồn đơn vị cơ sở."), ("min_quantity", "Ngưỡng cảnh báo."), ("updated_at", "Cập nhật biến động.")],
    "stockreceipts": [("id", "PK phiếu nhập."), ("receipt_code", "Mã phiếu duy nhất."), ("supplier_id", "FK suppliers."), ("staff_id", "FK users nhân viên."), ("receipt_date", "Ngày nhập."), ("status", "Draft/Pending/Approved/Rejected."), ("invoice_number", "Số hóa đơn NCC."), ("total_amount", "Tổng tiền."), ("notes", "Ghi chú."), ("approved_by", "FK users duyệt."), ("approved_at", "Thời điểm duyệt."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "salesorders": [("id", "PK đơn."), ("order_code", "Mã đơn duy nhất."), ("customer_id", "FK customers."), ("user_id", "FK users tạo đơn."), ("total_amount", "Tổng trước CK."), ("discount_amount", "Chiết khấu."), ("final_amount", "Generated: total - discount."), ("status", "Vòng đời đơn."), ("parent_order_id", "Đơn cha backorder."), ("shipping_address", "Địa chỉ giao."), ("notes", "Ghi chú."), ("created_at", "Tạo đơn."), ("updated_at", "Cập nhật."), ("cancelled_at", "Hủy lúc."), ("cancelled_by", "FK users hủy."), ("order_channel", "Retail/Wholesale/Return."), ("payment_status", "Paid/Unpaid/Partial."), ("ref_sales_order_id", "Đơn tham chiếu."), ("voucher_id", "FK vouchers."), ("pos_shift_ref", "Tham chiếu ca POS.")],
    "stockreceiptdetails": [("id", "PK dòng nhập."), ("receipt_id", "FK stockreceipts."), ("product_id", "FK products."), ("unit_id", "FK productunits."), ("quantity", "SL nhập."), ("cost_price", "Đơn giá vốn."), ("batch_number", "Số lô."), ("expiry_date", "Hạn dùng."), ("line_total", "Generated qty*cost."), ("created_at", "Tạo.")],
    "orderdetails": [("id", "PK dòng đơn."), ("order_id", "FK salesorders."), ("product_id", "FK products."), ("unit_id", "FK productunits."), ("quantity", "SL đặt."), ("price_at_time", "Đơn giá snapshot."), ("line_total", "Generated qty*price."), ("dispatched_qty", "Đã xuất kho."), ("created_at", "Tạo.")],
    "stockdispatches": [("id", "PK phiếu xuất."), ("dispatch_code", "Mã phiếu."), ("order_id", "FK salesorders.id (đơn nguồn, có thể NULL). Chuỗi: salesorders → stockdispatches(order_id) → stockdispatch_lines(dispatch_id)."), ("user_id", "FK users."), ("dispatch_date", "Ngày xuất."), ("status", "Pending/Full/Partial/..."), ("notes", "Ghi chú."), ("created_at", "Tạo."), ("updated_at", "Cập nhật."), ("reference_label", "Mô tả khi không có đơn."), ("deleted_at", "Xóa mềm."), ("deleted_by_user_id", "FK users xóa."), ("delete_reason", "Lý do xóa.")],
    "inventorylogs": [("id", "PK log tồn."), ("product_id", "FK products."), ("action_type", "INBOUND/OUTBOUND/TRANSFER/ADJUSTMENT."), ("quantity_change", "Biến động (+/-)."), ("unit_id", "FK productunits."), ("user_id", "FK users."), ("dispatch_id", "FK stockdispatches."), ("receipt_id", "FK stockreceipts."), ("from_location_id", "FK vị trí nguồn."), ("to_location_id", "FK vị trí đích."), ("reference_note", "Ghi chú tham chiếu."), ("created_at", "Thời điểm.")],
    "notifications": [("id", "PK thông báo."), ("user_id", "FK users nhận."), ("notification_type", "Loại in-app."), ("title", "Tiêu đề."), ("message", "Nội dung."), ("is_read", "Đã đọc."), ("reference_type", "Loại thực thể liên kết."), ("reference_id", "ID thực thể."), ("created_at", "Tạo."), ("read_at", "Thời điểm đọc.")],
    "storeprofiles": [("id", "PK hồ sơ."), ("owner_id", "FK users duy nhất."), ("name", "Tên cửa hàng."), ("business_category", "Ngành hàng."), ("address", "Địa chỉ."), ("phone", "SĐT."), ("email", "Email."), ("website", "Web."), ("tax_code", "MST."), ("footer_note", "Chân in bill."), ("logo_url", "Logo."), ("facebook_url", "FB."), ("instagram_handle", "IG."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "cashtransactions": [("id", "PK thu chi."), ("transaction_code", "Mã giao dịch."), ("direction", "Income/Expense."), ("amount", "Số tiền dương."), ("category", "Danh mục thu chi."), ("description", "Diễn giải."), ("payment_method", "Tiền mặt/CK..."), ("status", "Pending/Completed/Cancelled."), ("transaction_date", "Ngày chứng từ."), ("finance_ledger_id", "FK financeledger."), ("created_by", "FK users."), ("created_at", "Tạo."), ("updated_at", "Cập nhật."), ("fund_id", "FK cash_funds.")],
    "partnerdebts": [("id", "PK công nợ."), ("debt_code", "Mã công nợ."), ("partner_type", "Customer/Supplier."), ("customer_id", "FK customers."), ("supplier_id", "FK suppliers."), ("total_amount", "Tổng phải thu/chi."), ("paid_amount", "Đã thanh toán."), ("due_date", "Hạn."), ("status", "InDebt/Cleared."), ("notes", "Ghi chú."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "staffpasswordresetrequests": [("id", "PK yêu cầu."), ("user_id", "FK users nhân viên."), ("message", "Nội dung yêu cầu."), ("status", "Pending/Processed/Cancelled."), ("processed_by", "FK users xử lý."), ("created_at", "Tạo."), ("processed_at", "Xử lý lúc.")],
    "inventoryauditsessions": [("id", "PK phiên kiểm."), ("audit_code", "Mã phiên."), ("title", "Tiêu đề."), ("audit_date", "Ngày kiểm."), ("status", "Pending/In Progress/..."), ("location_filter", "Lọc vị trí."), ("category_filter", "Lọc danh mục."), ("notes", "Ghi chú."), ("created_by", "FK users tạo."), ("completed_at", "Hoàn tất."), ("completed_by", "FK users hoàn tất."), ("created_at", "Tạo."), ("updated_at", "Cập nhật."), ("deleted_at", "Xóa mềm."), ("owner_notes", "Ghi chú Owner.")],
    "inventoryauditlines": [("id", "PK dòng kiểm."), ("session_id", "FK inventoryauditsessions."), ("inventory_id", "FK inventory."), ("system_quantity", "SL hệ thống."), ("actual_quantity", "SL kiểm thực tế."), ("is_counted", "Đã đếm."), ("notes", "Ghi chú lệch."), ("variance_applied_at", "Áp dụng điều chỉnh."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "refresh_tokens": [("id", "PK token."), ("user_id", "FK users."), ("token", "Refresh token hash/UUID."), ("expires_at", "Hết hạn."), ("created_at", "Tạo."), ("delete_ymd", "Thu hồi soft-delete.")],
    "vouchers": [("id", "PK voucher."), ("code", "Mã quét duy nhất."), ("name", "Tên hiển thị."), ("discount_type", "Percent/FixedAmount."), ("discount_value", "Giá trị giảm."), ("is_active", "Đang dùng."), ("valid_from", "Hiệu lực từ."), ("valid_to", "Hiệu lực đến."), ("created_at", "Tạo."), ("updated_at", "Cập nhật."), ("used_count", "Số lần đã dùng."), ("max_uses", "Giới hạn lượt NULL=vô hạn.")],
    "voucher_redemptions": [("id", "PK redemption."), ("voucher_id", "FK vouchers."), ("sales_order_id", "FK salesorders."), ("created_at", "Thời điểm áp dụng.")],
    "inventory_audit_session_events": [("id", "PK sự kiện."), ("session_id", "FK inventoryauditsessions."), ("event_type", "Loại timeline."), ("payload", "JSON chi tiết."), ("created_by", "FK users."), ("created_at", "Thời điểm.")],
    "stockdispatch_lines": [("id", "PK dòng xuất."), ("dispatch_id", "FK stockdispatches.id — không phải salesorders.id; nối đơn qua stockdispatches.order_id."), ("inventory_id", "FK inventory."), ("quantity", "SL xuất."), ("unit_price_snapshot", "Đơn giá snapshot.")],
    "cash_funds": [("id", "PK quỹ."), ("code", "Mã quỹ duy nhất."), ("name", "Tên hiển thị."), ("is_default", "Quỹ mặc định."), ("is_active", "Đang dùng."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "ai_table_description": [("id", "PK registry bảng."), ("table_name", "Tên bảng lowercase duy nhất."), ("description", "Mô tả nghiệp vụ."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
    "ai_column_description": [("id", "PK registry cột."), ("table_name", "FK logical tới bảng."), ("column_name", "Tên cột lowercase."), ("description", "Mô tả nghiệp vụ cột."), ("created_at", "Tạo."), ("updated_at", "Cập nhật.")],
}

def esc(s):
    return s.replace("'", "''")

lines = []
for tbl, pairs in COLS.items():
    for col, desc in pairs:
        lines.append(f"        ('{tbl}', '{col}', '{esc(desc)}')")

out_path = "V45_column_values.sql"
with open(out_path, "w", encoding="utf-8") as f:
    f.write(",\n".join(lines))
print(len(lines), "->", out_path)