-- Registry mô tả nghiệp vụ theo cột cho AI (consumer: ai_python ColumnMeta.description + format_schema_block).
-- Phụ thuộc V44 ai_table_description: FK đảm bảo chỉ mô tả cột cho bảng đã đăng ký.

CREATE TABLE IF NOT EXISTS ai_column_description (
    id           BIGSERIAL PRIMARY KEY,
    table_name   VARCHAR(128) NOT NULL,
    column_name  VARCHAR(128) NOT NULL,
    description  TEXT           NOT NULL DEFAULT '',
    created_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ai_column_description_table_lower
        CHECK (table_name = lower(table_name)),
    CONSTRAINT ck_ai_column_description_table_nonempty
        CHECK (length(trim(table_name)) > 0),
    CONSTRAINT ck_ai_column_description_col_lower
        CHECK (column_name = lower(column_name)),
    CONSTRAINT ck_ai_column_description_col_nonempty
        CHECK (length(trim(column_name)) > 0),
    CONSTRAINT uq_ai_column_description_table_column UNIQUE (table_name, column_name),
    CONSTRAINT fk_ai_column_description_table
        FOREIGN KEY (table_name) REFERENCES ai_table_description (table_name) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ai_column_description_table_name
    ON ai_column_description (table_name);

COMMENT ON TABLE ai_column_description IS
    'Registry mô tả cột cho AI: một dòng / (table_name, column_name) chữ thường; join introspection information_schema.';

COMMENT ON COLUMN ai_column_description.table_name IS
    'Tên bảng PostgreSQL (lowercase), phải tồn tại trong ai_table_description.';

COMMENT ON COLUMN ai_column_description.column_name IS
    'Tên cột PostgreSQL (lowercase), khớp information_schema.columns.';

COMMENT ON COLUMN ai_column_description.description IS
    'Mô tả nghiệp vụ cột (tiếng Việt hoặc đa ngôn ngữ).';

-- Đăng ký bảng registry cột trong cùng registry bảng (meta).
INSERT INTO ai_table_description (table_name, description)
SELECT 'ai_column_description',
       'Registry mô tả theo cột (table_name, column_name) cho prompt AI; downstream merge vào SchemaArtifact.'
WHERE NOT EXISTS (
    SELECT 1 FROM ai_table_description t WHERE t.table_name = 'ai_column_description'
);

-- Seed idempotent: toàn bộ cột các bảng trong ai_table_description (V44 + meta ai_column_description).
INSERT INTO ai_column_description (table_name, column_name, description)
SELECT v.table_name, v.column_name, v.description
FROM (
    VALUES
        ('roles', 'id', 'PK vai trò.'),
        ('roles', 'name', 'Tên vai trò (Owner, Staff, Admin).'),
        ('roles', 'permissions', 'JSONB quyền menu/thao tác.'),
        ('roles', 'created_at', 'Thời điểm tạo bản ghi.'),
        ('categories', 'id', 'PK danh mục.'),
        ('categories', 'category_code', 'Mã danh mục duy nhất.'),
        ('categories', 'name', 'Tên hiển thị.'),
        ('categories', 'description', 'Mô tả chi tiết danh mục.'),
        ('categories', 'parent_id', 'FK danh mục cha (cây phân cấp).'),
        ('categories', 'sort_order', 'Thứ tự hiển thị.'),
        ('categories', 'status', 'Active/Inactive.'),
        ('categories', 'created_at', 'Tạo.'),
        ('categories', 'updated_at', 'Cập nhật cuối.'),
        ('suppliers', 'id', 'PK nhà cung cấp.'),
        ('suppliers', 'supplier_code', 'Mã NCC duy nhất.'),
        ('suppliers', 'name', 'Tên NCC.'),
        ('suppliers', 'contact_person', 'Người liên hệ.'),
        ('suppliers', 'phone', 'SĐT.'),
        ('suppliers', 'email', 'Email.'),
        ('suppliers', 'address', 'Địa chỉ.'),
        ('suppliers', 'tax_code', 'Mã số thuế.'),
        ('suppliers', 'status', 'Active/Inactive.'),
        ('suppliers', 'created_at', 'Tạo.'),
        ('suppliers', 'updated_at', 'Cập nhật.'),
        ('customers', 'id', 'PK khách hàng.'),
        ('customers', 'customer_code', 'Mã KH duy nhất.'),
        ('customers', 'name', 'Tên khách / tổ chức.'),
        ('customers', 'phone', 'SĐT bắt buộc.'),
        ('customers', 'email', 'Email.'),
        ('customers', 'address', 'Địa chỉ.'),
        ('customers', 'loyalty_points', 'Điểm tích lũy.'),
        ('customers', 'status', 'Active/Inactive.'),
        ('customers', 'created_at', 'Tạo.'),
        ('customers', 'updated_at', 'Cập nhật.'),
        ('warehouselocations', 'id', 'PK vị trí kho.'),
        ('warehouselocations', 'warehouse_code', 'Mã kho.'),
        ('warehouselocations', 'shelf_code', 'Mã kệ/vị trí.'),
        ('warehouselocations', 'description', 'Mô tả vị trí.'),
        ('warehouselocations', 'capacity', 'Sức chứa ước tính.'),
        ('warehouselocations', 'status', 'Active/Maintenance/Inactive.'),
        ('warehouselocations', 'created_at', 'Tạo.'),
        ('users', 'id', 'PK người dùng.'),
        ('users', 'username', 'Đăng nhập duy nhất.'),
        ('users', 'password_hash', 'Bcrypt/argon2 hash.'),
        ('users', 'full_name', 'Họ tên hiển thị.'),
        ('users', 'email', 'Email duy nhất.'),
        ('users', 'phone', 'SĐT.'),
        ('users', 'role_id', 'FK roles.'),
        ('users', 'status', 'Active/Locked.'),
        ('users', 'last_login', 'Đăng nhập gần nhất.'),
        ('users', 'created_at', 'Tạo.'),
        ('users', 'updated_at', 'Cập nhật.'),
        ('products', 'id', 'PK sản phẩm.'),
        ('products', 'category_id', 'FK categories.'),
        ('products', 'sku_code', 'Mã SKU duy nhất.'),
        ('products', 'barcode', 'Mã vạch.'),
        ('products', 'name', 'Tên sản phẩm.'),
        ('products', 'image_url', 'URL ảnh đại diện.'),
        ('products', 'description', 'Mô tả dài.'),
        ('products', 'weight', 'Khối lượng gram.'),
        ('products', 'status', 'Active/Inactive.'),
        ('products', 'created_at', 'Tạo.'),
        ('products', 'updated_at', 'Cập nhật.'),
        ('productimages', 'id', 'PK ảnh.'),
        ('productimages', 'product_id', 'FK products.'),
        ('productimages', 'image_url', 'URL ảnh.'),
        ('productimages', 'alt_text', 'Alt SEO.'),
        ('productimages', 'is_primary', 'Ảnh chính.'),
        ('productimages', 'sort_order', 'Thứ tự carousel.'),
        ('productimages', 'file_size_bytes', 'Kích thước file.'),
        ('productimages', 'mime_type', 'MIME.'),
        ('productimages', 'created_at', 'Tạo.'),
        ('alertsettings', 'id', 'PK cảnh báo.'),
        ('alertsettings', 'owner_id', 'FK users chủ cấu hình.'),
        ('alertsettings', 'alert_type', 'Loại: LowStock, ExpiryDate, ...'),
        ('alertsettings', 'threshold_value', 'Ngưỡng kích hoạt.'),
        ('alertsettings', 'channel', 'App/Email/SMS/Zalo.'),
        ('alertsettings', 'frequency', 'Realtime/Daily/Weekly.'),
        ('alertsettings', 'is_enabled', 'Bật/tắt.'),
        ('alertsettings', 'recipients', 'JSON người nhận thêm.'),
        ('alertsettings', 'created_at', 'Tạo.'),
        ('alertsettings', 'updated_at', 'Cập nhật.'),
        ('systemlogs', 'id', 'PK log.'),
        ('systemlogs', 'log_level', 'INFO/WARNING/ERROR/CRITICAL.'),
        ('systemlogs', 'module', 'Module nguồn.'),
        ('systemlogs', 'action', 'Hành động.'),
        ('systemlogs', 'user_id', 'FK users (nullable).'),
        ('systemlogs', 'message', 'Nội dung log.'),
        ('systemlogs', 'stack_trace', 'Stack khi lỗi.'),
        ('systemlogs', 'context_data', 'JSON bổ sung.'),
        ('systemlogs', 'created_at', 'Thời điểm ghi.'),
        ('financeledger', 'id', 'PK bút toán.'),
        ('financeledger', 'transaction_date', 'Ngày chứng từ.'),
        ('financeledger', 'transaction_type', 'Doanh thu/Chi phí/...'),
        ('financeledger', 'reference_type', 'Loại chứng từ nguồn.'),
        ('financeledger', 'reference_id', 'ID chứng từ nguồn.'),
        ('financeledger', 'amount', 'Dương thu âm chi.'),
        ('financeledger', 'description', 'Diễn giải.'),
        ('financeledger', 'created_by', 'FK users lập.'),
        ('financeledger', 'created_at', 'Tạo.'),
        ('financeledger', 'updated_at', 'Cập nhật.'),
        ('financeledger', 'fund_id', 'FK cash_funds (đa quỹ).'),
        ('aiinsights', 'id', 'PK insight.'),
        ('aiinsights', 'owner_id', 'FK users.'),
        ('aiinsights', 'dashboard_snapshot', 'JSON snapshot dashboard.'),
        ('aiinsights', 'prompt', 'Prompt gửi LLM.'),
        ('aiinsights', 'ai_advice', 'Kết quả markdown.'),
        ('aiinsights', 'model_used', 'Tên model.'),
        ('aiinsights', 'tokens_used', 'Token tiêu thụ.'),
        ('aiinsights', 'created_at', 'Tạo.'),
        ('aichathistory', 'id', 'PK tin nhắn.'),
        ('aichathistory', 'user_id', 'FK users.'),
        ('aichathistory', 'session_id', 'Phiên chat.'),
        ('aichathistory', 'message', 'Nội dung.'),
        ('aichathistory', 'sender', 'User/Bot.'),
        ('aichathistory', 'intent', 'JSON intent nhận dạng.'),
        ('aichathistory', 'response_time_ms', 'Độ trễ phản hồi.'),
        ('aichathistory', 'created_at', 'Tạo.'),
        ('mediaaudits', 'id', 'PK audit media.'),
        ('mediaaudits', 'file_type', 'OCR_Image/Voice_Audio.'),
        ('mediaaudits', 'cloud_url', 'URL cloud.'),
        ('mediaaudits', 'entity_type', 'Loại thực thể.'),
        ('mediaaudits', 'entity_id', 'ID thực thể.'),
        ('mediaaudits', 'file_size_bytes', 'Kích thước.'),
        ('mediaaudits', 'mime_type', 'MIME.'),
        ('mediaaudits', 'uploaded_by', 'FK users.'),
        ('mediaaudits', 'created_at', 'Tạo.'),
        ('productunits', 'id', 'PK đơn vị.'),
        ('productunits', 'product_id', 'FK products.'),
        ('productunits', 'unit_name', 'Tên đơn vị (Thùng, Lon).'),
        ('productunits', 'conversion_rate', 'Quy đổi về base unit.'),
        ('productunits', 'is_base_unit', 'Đơn vị cơ sở duy nhất.'),
        ('productunits', 'created_at', 'Tạo.'),
        ('productunits', 'updated_at', 'Cập nhật.'),
        ('productpricehistory', 'id', 'PK lịch sử giá.'),
        ('productpricehistory', 'product_id', 'FK products.'),
        ('productpricehistory', 'unit_id', 'FK productunits.'),
        ('productpricehistory', 'cost_price', 'Giá vốn.'),
        ('productpricehistory', 'sale_price', 'Giá bán.'),
        ('productpricehistory', 'effective_date', 'Ngày hiệu lực.'),
        ('productpricehistory', 'created_at', 'Tạo.'),
        ('inventory', 'id', 'PK tồn lô.'),
        ('inventory', 'product_id', 'FK products.'),
        ('inventory', 'location_id', 'FK warehouselocations.'),
        ('inventory', 'batch_number', 'Số lô.'),
        ('inventory', 'expiry_date', 'Hạn dùng.'),
        ('inventory', 'quantity', 'SL tồn đơn vị cơ sở.'),
        ('inventory', 'min_quantity', 'Ngưỡng cảnh báo.'),
        ('inventory', 'updated_at', 'Cập nhật biến động.'),
        ('stockreceipts', 'id', 'PK phiếu nhập.'),
        ('stockreceipts', 'receipt_code', 'Mã phiếu duy nhất.'),
        ('stockreceipts', 'supplier_id', 'FK suppliers.'),
        ('stockreceipts', 'staff_id', 'FK users nhân viên.'),
        ('stockreceipts', 'receipt_date', 'Ngày nhập.'),
        ('stockreceipts', 'status', 'Draft/Pending/Approved/Rejected.'),
        ('stockreceipts', 'invoice_number', 'Số hóa đơn NCC.'),
        ('stockreceipts', 'total_amount', 'Tổng tiền.'),
        ('stockreceipts', 'notes', 'Ghi chú.'),
        ('stockreceipts', 'approved_by', 'FK users duyệt.'),
        ('stockreceipts', 'approved_at', 'Thời điểm duyệt.'),
        ('stockreceipts', 'created_at', 'Tạo.'),
        ('stockreceipts', 'updated_at', 'Cập nhật.'),
        ('salesorders', 'id', 'PK đơn.'),
        ('salesorders', 'order_code', 'Mã đơn duy nhất.'),
        ('salesorders', 'customer_id', 'FK customers.'),
        ('salesorders', 'user_id', 'FK users tạo đơn.'),
        ('salesorders', 'total_amount', 'Tổng trước CK.'),
        ('salesorders', 'discount_amount', 'Chiết khấu.'),
        ('salesorders', 'final_amount', 'Generated: total - discount.'),
        ('salesorders', 'status', 'Vòng đời đơn.'),
        ('salesorders', 'parent_order_id', 'Đơn cha backorder.'),
        ('salesorders', 'shipping_address', 'Địa chỉ giao.'),
        ('salesorders', 'notes', 'Ghi chú.'),
        ('salesorders', 'created_at', 'Tạo đơn.'),
        ('salesorders', 'updated_at', 'Cập nhật.'),
        ('salesorders', 'cancelled_at', 'Hủy lúc.'),
        ('salesorders', 'cancelled_by', 'FK users hủy.'),
        ('salesorders', 'order_channel', 'Retail/Wholesale/Return.'),
        ('salesorders', 'payment_status', 'Paid/Unpaid/Partial.'),
        ('salesorders', 'ref_sales_order_id', 'Đơn tham chiếu.'),
        ('salesorders', 'voucher_id', 'FK vouchers.'),
        ('salesorders', 'pos_shift_ref', 'Tham chiếu ca POS.'),
        ('stockreceiptdetails', 'id', 'PK dòng nhập.'),
        ('stockreceiptdetails', 'receipt_id', 'FK stockreceipts.'),
        ('stockreceiptdetails', 'product_id', 'FK products.'),
        ('stockreceiptdetails', 'unit_id', 'FK productunits.'),
        ('stockreceiptdetails', 'quantity', 'SL nhập.'),
        ('stockreceiptdetails', 'cost_price', 'Đơn giá vốn.'),
        ('stockreceiptdetails', 'batch_number', 'Số lô.'),
        ('stockreceiptdetails', 'expiry_date', 'Hạn dùng.'),
        ('stockreceiptdetails', 'line_total', 'Generated qty*cost.'),
        ('stockreceiptdetails', 'created_at', 'Tạo.'),
        ('orderdetails', 'id', 'PK dòng đơn.'),
        ('orderdetails', 'order_id', 'FK salesorders.'),
        ('orderdetails', 'product_id', 'FK products.'),
        ('orderdetails', 'unit_id', 'FK productunits.'),
        ('orderdetails', 'quantity', 'SL đặt.'),
        ('orderdetails', 'price_at_time', 'Đơn giá snapshot.'),
        ('orderdetails', 'line_total', 'Generated qty*price.'),
        ('orderdetails', 'dispatched_qty', 'Đã xuất kho.'),
        ('orderdetails', 'created_at', 'Tạo.'),
        ('stockdispatches', 'id', 'PK phiếu xuất.'),
        ('stockdispatches', 'dispatch_code', 'Mã phiếu.'),
        ('stockdispatches', 'order_id', 'FK salesorders nullable.'),
        ('stockdispatches', 'user_id', 'FK users.'),
        ('stockdispatches', 'dispatch_date', 'Ngày xuất.'),
        ('stockdispatches', 'status', 'Pending/Full/Partial/...'),
        ('stockdispatches', 'notes', 'Ghi chú.'),
        ('stockdispatches', 'created_at', 'Tạo.'),
        ('stockdispatches', 'updated_at', 'Cập nhật.'),
        ('stockdispatches', 'reference_label', 'Mô tả khi không có đơn.'),
        ('stockdispatches', 'deleted_at', 'Xóa mềm.'),
        ('stockdispatches', 'deleted_by_user_id', 'FK users xóa.'),
        ('stockdispatches', 'delete_reason', 'Lý do xóa.'),
        ('inventorylogs', 'id', 'PK log tồn.'),
        ('inventorylogs', 'product_id', 'FK products.'),
        ('inventorylogs', 'action_type', 'INBOUND/OUTBOUND/TRANSFER/ADJUSTMENT.'),
        ('inventorylogs', 'quantity_change', 'Biến động (+/-).'),
        ('inventorylogs', 'unit_id', 'FK productunits.'),
        ('inventorylogs', 'user_id', 'FK users.'),
        ('inventorylogs', 'dispatch_id', 'FK stockdispatches.'),
        ('inventorylogs', 'receipt_id', 'FK stockreceipts.'),
        ('inventorylogs', 'from_location_id', 'FK vị trí nguồn.'),
        ('inventorylogs', 'to_location_id', 'FK vị trí đích.'),
        ('inventorylogs', 'reference_note', 'Ghi chú tham chiếu.'),
        ('inventorylogs', 'created_at', 'Thời điểm.'),
        ('notifications', 'id', 'PK thông báo.'),
        ('notifications', 'user_id', 'FK users nhận.'),
        ('notifications', 'notification_type', 'Loại in-app.'),
        ('notifications', 'title', 'Tiêu đề.'),
        ('notifications', 'message', 'Nội dung.'),
        ('notifications', 'is_read', 'Đã đọc.'),
        ('notifications', 'reference_type', 'Loại thực thể liên kết.'),
        ('notifications', 'reference_id', 'ID thực thể.'),
        ('notifications', 'created_at', 'Tạo.'),
        ('notifications', 'read_at', 'Thời điểm đọc.'),
        ('storeprofiles', 'id', 'PK hồ sơ.'),
        ('storeprofiles', 'owner_id', 'FK users duy nhất.'),
        ('storeprofiles', 'name', 'Tên cửa hàng.'),
        ('storeprofiles', 'business_category', 'Ngành hàng.'),
        ('storeprofiles', 'address', 'Địa chỉ.'),
        ('storeprofiles', 'phone', 'SĐT.'),
        ('storeprofiles', 'email', 'Email.'),
        ('storeprofiles', 'website', 'Web.'),
        ('storeprofiles', 'tax_code', 'MST.'),
        ('storeprofiles', 'footer_note', 'Chân in bill.'),
        ('storeprofiles', 'logo_url', 'Logo.'),
        ('storeprofiles', 'facebook_url', 'FB.'),
        ('storeprofiles', 'instagram_handle', 'IG.'),
        ('storeprofiles', 'created_at', 'Tạo.'),
        ('storeprofiles', 'updated_at', 'Cập nhật.'),
        ('cashtransactions', 'id', 'PK thu chi.'),
        ('cashtransactions', 'transaction_code', 'Mã giao dịch.'),
        ('cashtransactions', 'direction', 'Income/Expense.'),
        ('cashtransactions', 'amount', 'Số tiền dương.'),
        ('cashtransactions', 'category', 'Danh mục thu chi.'),
        ('cashtransactions', 'description', 'Diễn giải.'),
        ('cashtransactions', 'payment_method', 'Tiền mặt/CK...'),
        ('cashtransactions', 'status', 'Pending/Completed/Cancelled.'),
        ('cashtransactions', 'transaction_date', 'Ngày chứng từ.'),
        ('cashtransactions', 'finance_ledger_id', 'FK financeledger.'),
        ('cashtransactions', 'created_by', 'FK users.'),
        ('cashtransactions', 'created_at', 'Tạo.'),
        ('cashtransactions', 'updated_at', 'Cập nhật.'),
        ('cashtransactions', 'fund_id', 'FK cash_funds.'),
        ('partnerdebts', 'id', 'PK công nợ.'),
        ('partnerdebts', 'debt_code', 'Mã công nợ.'),
        ('partnerdebts', 'partner_type', 'Customer/Supplier.'),
        ('partnerdebts', 'customer_id', 'FK customers.'),
        ('partnerdebts', 'supplier_id', 'FK suppliers.'),
        ('partnerdebts', 'total_amount', 'Tổng phải thu/chi.'),
        ('partnerdebts', 'paid_amount', 'Đã thanh toán.'),
        ('partnerdebts', 'due_date', 'Hạn.'),
        ('partnerdebts', 'status', 'InDebt/Cleared.'),
        ('partnerdebts', 'notes', 'Ghi chú.'),
        ('partnerdebts', 'created_at', 'Tạo.'),
        ('partnerdebts', 'updated_at', 'Cập nhật.'),
        ('staffpasswordresetrequests', 'id', 'PK yêu cầu.'),
        ('staffpasswordresetrequests', 'user_id', 'FK users nhân viên.'),
        ('staffpasswordresetrequests', 'message', 'Nội dung yêu cầu.'),
        ('staffpasswordresetrequests', 'status', 'Pending/Processed/Cancelled.'),
        ('staffpasswordresetrequests', 'processed_by', 'FK users xử lý.'),
        ('staffpasswordresetrequests', 'created_at', 'Tạo.'),
        ('staffpasswordresetrequests', 'processed_at', 'Xử lý lúc.'),
        ('inventoryauditsessions', 'id', 'PK phiên kiểm.'),
        ('inventoryauditsessions', 'audit_code', 'Mã phiên.'),
        ('inventoryauditsessions', 'title', 'Tiêu đề.'),
        ('inventoryauditsessions', 'audit_date', 'Ngày kiểm.'),
        ('inventoryauditsessions', 'status', 'Pending/In Progress/...'),
        ('inventoryauditsessions', 'location_filter', 'Lọc vị trí.'),
        ('inventoryauditsessions', 'category_filter', 'Lọc danh mục.'),
        ('inventoryauditsessions', 'notes', 'Ghi chú.'),
        ('inventoryauditsessions', 'created_by', 'FK users tạo.'),
        ('inventoryauditsessions', 'completed_at', 'Hoàn tất.'),
        ('inventoryauditsessions', 'completed_by', 'FK users hoàn tất.'),
        ('inventoryauditsessions', 'created_at', 'Tạo.'),
        ('inventoryauditsessions', 'updated_at', 'Cập nhật.'),
        ('inventoryauditsessions', 'deleted_at', 'Xóa mềm.'),
        ('inventoryauditsessions', 'owner_notes', 'Ghi chú Owner.'),
        ('inventoryauditlines', 'id', 'PK dòng kiểm.'),
        ('inventoryauditlines', 'session_id', 'FK inventoryauditsessions.'),
        ('inventoryauditlines', 'inventory_id', 'FK inventory.'),
        ('inventoryauditlines', 'system_quantity', 'SL hệ thống.'),
        ('inventoryauditlines', 'actual_quantity', 'SL kiểm thực tế.'),
        ('inventoryauditlines', 'is_counted', 'Đã đếm.'),
        ('inventoryauditlines', 'notes', 'Ghi chú lệch.'),
        ('inventoryauditlines', 'variance_applied_at', 'Áp dụng điều chỉnh.'),
        ('inventoryauditlines', 'created_at', 'Tạo.'),
        ('inventoryauditlines', 'updated_at', 'Cập nhật.'),
        ('refresh_tokens', 'id', 'PK token.'),
        ('refresh_tokens', 'user_id', 'FK users.'),
        ('refresh_tokens', 'token', 'Refresh token hash/UUID.'),
        ('refresh_tokens', 'expires_at', 'Hết hạn.'),
        ('refresh_tokens', 'created_at', 'Tạo.'),
        ('refresh_tokens', 'delete_ymd', 'Thu hồi soft-delete.'),
        ('vouchers', 'id', 'PK voucher.'),
        ('vouchers', 'code', 'Mã quét duy nhất.'),
        ('vouchers', 'name', 'Tên hiển thị.'),
        ('vouchers', 'discount_type', 'Percent/FixedAmount.'),
        ('vouchers', 'discount_value', 'Giá trị giảm.'),
        ('vouchers', 'is_active', 'Đang dùng.'),
        ('vouchers', 'valid_from', 'Hiệu lực từ.'),
        ('vouchers', 'valid_to', 'Hiệu lực đến.'),
        ('vouchers', 'created_at', 'Tạo.'),
        ('vouchers', 'updated_at', 'Cập nhật.'),
        ('vouchers', 'used_count', 'Số lần đã dùng.'),
        ('vouchers', 'max_uses', 'Giới hạn lượt NULL=vô hạn.'),
        ('voucher_redemptions', 'id', 'PK redemption.'),
        ('voucher_redemptions', 'voucher_id', 'FK vouchers.'),
        ('voucher_redemptions', 'sales_order_id', 'FK salesorders.'),
        ('voucher_redemptions', 'created_at', 'Thời điểm áp dụng.'),
        ('inventory_audit_session_events', 'id', 'PK sự kiện.'),
        ('inventory_audit_session_events', 'session_id', 'FK inventoryauditsessions.'),
        ('inventory_audit_session_events', 'event_type', 'Loại timeline.'),
        ('inventory_audit_session_events', 'payload', 'JSON chi tiết.'),
        ('inventory_audit_session_events', 'created_by', 'FK users.'),
        ('inventory_audit_session_events', 'created_at', 'Thời điểm.'),
        ('stockdispatch_lines', 'id', 'PK dòng xuất.'),
        ('stockdispatch_lines', 'dispatch_id', 'FK stockdispatches.'),
        ('stockdispatch_lines', 'inventory_id', 'FK inventory.'),
        ('stockdispatch_lines', 'quantity', 'SL xuất.'),
        ('stockdispatch_lines', 'unit_price_snapshot', 'Đơn giá snapshot.'),
        ('cash_funds', 'id', 'PK quỹ.'),
        ('cash_funds', 'code', 'Mã quỹ duy nhất.'),
        ('cash_funds', 'name', 'Tên hiển thị.'),
        ('cash_funds', 'is_default', 'Quỹ mặc định.'),
        ('cash_funds', 'is_active', 'Đang dùng.'),
        ('cash_funds', 'created_at', 'Tạo.'),
        ('cash_funds', 'updated_at', 'Cập nhật.'),
        ('ai_table_description', 'id', 'PK registry bảng.'),
        ('ai_table_description', 'table_name', 'Tên bảng lowercase duy nhất.'),
        ('ai_table_description', 'description', 'Mô tả nghiệp vụ.'),
        ('ai_table_description', 'created_at', 'Tạo.'),
        ('ai_table_description', 'updated_at', 'Cập nhật.'),
        ('ai_column_description', 'id', 'PK registry cột.'),
        ('ai_column_description', 'table_name', 'FK logical tới bảng.'),
        ('ai_column_description', 'column_name', 'Tên cột lowercase.'),
        ('ai_column_description', 'description', 'Mô tả nghiệp vụ cột.'),
        ('ai_column_description', 'created_at', 'Tạo.'),
        ('ai_column_description', 'updated_at', 'Cập nhật.')
) AS v(table_name, column_name, description)
WHERE EXISTS (SELECT 1 FROM ai_table_description t WHERE t.table_name = v.table_name)
  AND NOT EXISTS (
        SELECT 1
        FROM ai_column_description c
        WHERE c.table_name = v.table_name AND c.column_name = v.column_name
    );
