-- Task103 — Bổ sung mô tả bảng chi tiết cho AI (UC/schema/ER + migration BE).
-- Cập nhật idempotent: ghi đè description + updated_at cho mọi dòng đã seed V44 và meta V45.

UPDATE ai_table_description AS t
SET description = v.description,
    updated_at  = CURRENT_TIMESTAMP
FROM (
    VALUES
        ('roles', $r01$Bảng master vai trò (Owner, Staff, Admin) và ma trận quyền JSONB (menu, thao tác, phê duyệt). Chức năng: chuẩn hóa phân quyền tập trung thay vì hard-code ở từng user. Ảnh hưởng tới: khả năng truy cập module, quyền phê duyệt phiếu/tài chính, và mọi báo cáo giới hạn theo role. Bảng liên quan: users (role_id RESTRICT — không xóa role khi còn user). Đọc khi: UC3 (Manage Staff Accounts), cấu hình đăng nhập/ủy quyền, và mọi luồng cần biết quyền hiện tại của nhân viên.$r01$),
        ('categories', $r02$Danh mục sản phẩm dạng cây (parent_id, sort_order, status) kèm mã danh mục duy nhất. Chức năng: nhóm hàng cho báo cáo, lọc kho/POS và hiển thị UI. Ảnh hưởng tới: phân loại doanh thu/tồn kho theo nhóm, điều kiện lọc kiểm kê (category_filter trên phiên kiểm kê nếu áp dụng), và trải nghiệm duyệt catalog. Bảng liên quan: categories (tự tham chiếu cha-con), products (category_id SET NULL khi xóa danh mục). Đọc khi: UC6 (Manage inventory list), UC8 (Manage Products), dashboard/thống kê theo nhóm hàng.$r02$),
        ('suppliers', $r03$Master nhà cung cấp (mã, liên hệ, MST, trạng thái Active/Inactive). Chức năng: định danh nguồn nhập và công nợ phía mua hàng. Ảnh hưởng tới: giá vốn phiếu nhập, lịch sử mua, công nợ NCC (partnerdebts partner_type Supplier), và báo cáo mua hàng. Bảng liên quan: stockreceipts (supplier_id RESTRICT), partnerdebts (supplier_id). Đọc khi: UC7 (Manage stock receipts), UC8 (Manage Products — thông tin NCC tham chiếu), UC12 (Update via Image — phiếu nhập/ảnh minh chứng).$r03$),
        ('customers', $r04$Master khách hàng (mã, liên hệ, điểm tích lũy, trạng thái). Chức năng: định danh đơn bán, POS walk-in/KH đăng ký và theo dõi chi tiêu. Ảnh hưởng tới: doanh thu theo KH, công nợ phải thu (partnerdebts Customer), loyalty_points, và các KPI bán hàng trên dashboard. Bảng liên quan: salesorders (customer_id RESTRICT), partnerdebts (customer_id). Đọc khi: UC9 (Manage Sales Orders), UC1 (Dashboard — tổng quan bán hàng khi join đơn), các báo cáo công nợ khách.$r04$),
        ('warehouselocations', $r05$Master vị trí lưu kho (kệ/khu/mã vị trí). Chức năng: định vị tồn theo không gian vật lý để nhập/xuất/kiểm kê chính xác. Ảnh hưởng tới: bản đồ tồn theo vị trí, điều kiện lọc kiểm kê (location_filter), và luồng xuất/chuyển kho có from/to location trên nhật ký. Bảng liên quan: inventory (location_id RESTRICT khi còn tồn), inventorylogs (from_location_id, to_location_id). Đọc khi: UC6 (Manage inventory), UC10 (Dispatch / xuất kho), UC13 (Voice update — truy vấn tồn theo vị trí nếu có).$r05$),
        ('users', $r06$Tài khoản người dùng nội bộ (username, email, hash mật khẩu, họ tên, role, Active/Locked, last_login). Chức năng: xác thực, gán quyền và làm khóa ngoại audit trên hầu hết giao dịch. Ảnh hưởng tới: vết truy vết người tạo/duyệt/hủy, khóa tài khoản (Locked), và phạm vi dữ liệu cá nhân (alert, AI chat, notification). Bảng liên quan: roles (role_id), refresh_tokens; là cha của/được tham chiếu bởi stockreceipts (staff_id, approved_by), salesorders (user_id, cancelled_by), stockdispatches (user_id), financeledger (created_by), systemlogs, notifications, storeprofiles (owner_id), cashtransactions (created_by), inventoryauditsessions (created_by, completed_by), v.v. Đọc khi: hầu hết UC1–UC13 (auth + audit trail theo schema.sql).$r06$),
        ('products', $r07$Master sản phẩm (SKU, tên, đơn vị cơ sở, giá, trạng thái KD, liên kết danh mục). Chức năng: hạt nhân dữ liệu cho tồn kho, đơn hàng, nhập xuất và báo cáo. Ảnh hưởng tới: giá trị tồn kho, doanh thu/COGS trên đơn, điều kiện cảnh báo hết hàng, và mọi truy vấn “bán được gì / còn bao nhiêu”. Bảng liên quan: categories, productimages, productunits, productpricehistory, inventory, stockreceiptdetails, orderdetails, inventorylogs. Đọc khi: UC1 (Dashboard), UC6, UC7, UC8, UC9, UC10, UC11 (ChatBot tra cứu hàng), UC12, UC13.$r07$),
        ('productimages', $r08$Ảnh minh họa sản phẩm (URL, cờ primary, thứ tự). Chức năng: phục vụ UI catalog/POS và đồng bộ media audit. Ảnh hưởng tới: trải nghiệm duyệt hàng, nhận diện thị giác khi nhập/xuất (UC12), không ảnh hưởng trực tiếp số lượng tồn hay giá. Bảng liên quan: products (product_id CASCADE). Đọc khi: UC8 (Manage Products), UC12 (Update via Image).$r08$),
        ('alertsettings', $r09$Cấu hình ngưỡng cảnh báo (tồn tối thiểu, hạn dùng, kênh thông báo) theo owner/user. Chức năng: điều khiển khi nào hệ thống cảnh báo hết hàng/hết date. Ảnh hưởng tới: danh sách cảnh báo trên dashboard, notification tiềm năng, và quyết định bổ sung hàng. Bảng liên quan: users (owner_id CASCADE). Đọc khi: UC5 (Configure Alert Settings), UC1 khi hiển thị trạng thái cảnh báo tồn.$r09$),
        ('systemlogs', $r10$Nhật ký hành động hệ thống (entity, hành động, payload tóm tắt, user). Chức năng: audit read-heavy cho vận hành và an toàn. Ảnh hưởng tới: truy vết ai thao tác gì (không thay thế bút toán kế toán); hỗ trợ điều tra sai lệch quy trình. Bảng liên quan: users (user_id SET NULL). Đọc khi: UC4 (Approve Transactions — đối soát), UC6 (Manage inventory — theo dõi thay đổi), quản trị/viewer log.$r10$),
        ('financeledger', $r11$Sổ cái kế toán (nợ/có, số dư lũy kế, liên kết chứng từ đa hình, fund_id NOT NULL tới cash_funds theo V41). Chức năng: ghi nhận bút toán từ phiếu nhập đã duyệt, thu chi hoàn tất, và luồng tài chính khác. Ảnh hưởng tới: báo cáo lãi/lỗ, số dư theo quỹ, đối soát với cashtransactions (finance_ledger_id). Bảng liên quan: users (created_by RESTRICT), cash_funds (fund_id), cashtransactions, stockreceipts (khi duyệt sinh ledger — theo nghiệp vụ BE). Đọc khi: UC1 (Dashboard tài chính), UC4 (Approve Transactions).$r11$),
        ('aiinsights', $r12$Bản ghi insight/gợi ý AI theo owner (tiêu đề, nội dung, metadata). Chức năng: lưu kết quả phân tích tự động phục vụ dashboard và lịch sử xem lại. Ảnh hưởng tới: trải nghiệm “AI Business Insight”, không là nguồn số liệu kế toán chính thức. Bảng liên quan: users (owner_id CASCADE). Đọc khi: UC1 (Dashboard), UC2 (AI Business Insight).$r12$),
        ('aichathistory', $r13$Lưu vết hội thoại chat AI theo user (prompt/response theo thiết kế bảo mật). Chức năng: tiếp tục ngữ cảnh hội thoại và phân tích hành vi dùng AI. Ảnh hưởng tới: tuân thủ lưu trữ/lộ lọc PII — chỉ dùng cho module AI, không điều khiển tồn tiền. Bảng liên quan: users (user_id CASCADE). Đọc khi: UC2 (AI Business Insight), UC11 (Interact with ChatBot).$r13$),
        ('mediaaudits', $r14$Theo dõi thao tác file media (upload/xóa) đa hình (polymorphic tới receipt/order/inventory). Chức năng: chứng từ điện tử và truy vết thay đổi hình ảnh/giọng nói liên quan chứng từ. Ảnh hưởng tới: tuân thủ và đối soát chứng từ, không thay đổi số lượng tồn trực tiếp. Bảng liên quan: users (uploaded_by SET NULL). Đọc khi: UC12 (Update via Image), UC13 (Update via Voice).$r14$),
        ('productunits', $r15$Đơn vị quy đổi theo từng SKU (hệ số so đơn vị cơ sở, làm tròn). Chức năng: cho phép nhập/bán/kiểm kê theo thùng/lẻ với quy đổi thống nhất. Ảnh hưởng tới: số lượng quy đổi trên phiếu nhập/chi tiết đơn, giá theo đơn vị trong productpricehistory (unit_id), và log tồn. Bảng liên quan: products (CASCADE), productpricehistory, stockreceiptdetails, orderdetails, inventorylogs. Đọc khi: UC6, UC7, UC8, UC9, UC10, UC13.$r15$),
        ('productpricehistory', $r16$Lịch sử giá niêm yết/bán theo thời gian và đơn vị. Chức năng: giải thích biến động margin, audit giá và báo cáo xu hướng. Ảnh hưởng tới: KPI giá trung bình theo thời kỳ, so sánh với doanh thu đơn hàng cùng kỳ. Bảng liên quan: products, productunits. Đọc khi: UC1 (Dashboard — biểu đồ giá/biên lợi nhuận nếu có), UC8 (Manage Products).$r16$),
        ('inventory', $r17$Tồn kho vật lý theo (product, batch/lot, location, expiry). Chức năng: nguồn sự thật cho “còn bao nhiêu ở đâu”. Ảnh hưởng tới: tổng giá trị tồn kho dashboard, khả năng xuất/hủy, kiểm kê (inventoryauditlines.inventory_id), và cảnh báo hết hạn. Bảng liên quan: products, warehouselocations, inventoryauditlines, inventorylogs (gián tiếp qua giao dịch). Đọc khi: UC1, UC4 (duyệt liên quan tồn), UC6, UC9 (kiểm tra hàng trước bán), UC10.$r17$),
        ('stockreceipts', $r18$Phiếu nhập kho (NCC, trạng thái chờ duyệt/đã duyệt, staff, approver, ngày). Chức năng: quy trình nhập hàng có kiểm soát và sinh tồn + bút toán khi duyệt. Ảnh hưởng tới: tồn kho, giá vốn, công nợ NCC, financeledger (khi approved), và media chứng từ. Bảng liên quan: suppliers, users (staff_id, approved_by), stockreceiptdetails, inventorylogs, financeledger. Đọc khi: UC4 (Approve), UC7 (Manage stock receipts), UC12.$r18$),
        ('salesorders', $r19$Đơn bán (khách, kênh, thanh toán, trạng thái, tổng tiền, parent/backorder). Chức năng: nguồn doanh thu và nền cho xuất kho/POS/voucher. Ảnh hưởng tới: doanh thu, công nợ KH, khả năng giao (reservation) và KPI bán theo kênh. Bảng liên quan: customers, users, orderdetails, stockdispatches (order_id), voucher_redemptions, partnerdebts (gián tiếp qua nghiệp vụ công nợ). Đọc khi: UC1, UC4, UC9, UC10.$r19$),
        ('stockreceiptdetails', $r20$Dòng phiếu nhập (sản phẩm, đơn vị, SL, đơn giá, lô). Chức năng: chi tiết hóa giá trị và lô nhập để cộng tồn. Ảnh hưởng tới: tồn theo lô, giá vốn trung bình, và đối soát với inventorylogs khi post. Bảng liên quan: stockreceipts (CASCADE), products, productunits. Đọc khi: UC7, UC12.$r20$),
        ('orderdetails', $r21$Dòng đơn bán (SKU, đơn vị, SL đặt, đơn giá, chiết khấu, delivered_qty). Chức năng: tính tiền hàng và theo dõi đáp ứng từng dòng. Ảnh hưởng tới: doanh thu chi tiết, margin theo SKU; xuất kho thực tế thường đi qua stockdispatches (order_id) và stockdispatch_lines gắn inventory/lô chứ không FK trực tiếp từ dòng này. Bảng liên quan: salesorders (CASCADE), products, productunits. Đọc khi: UC9, UC10.$r21$),
        ('stockdispatches', $r22$Phiếu xuất kho cấp header (loại xuất, trạng thái, liên kết đơn bán nếu có). Chức năng: gom các dòng xuất (stockdispatch_lines) và làm cầu nối tới salesorders. Ảnh hưởng tới: khả năng trừ tồn, chi phí giao hàng/xuất kho, và inventorylogs (dispatch_id). Bảng liên quan: salesorders (order_id RESTRICT — không xóa đơn khi còn phiếu xuất), users, stockdispatch_lines, inventorylogs. Đọc khi: UC4 (phê duyệt liên quan xuất), UC10 (Dispatch).$r22$),
        ('inventorylogs', $r23$Nhật ký biến động tồn theo từng lô (nhập/xuất/điều chỉnh/kiểm kê). Chức năng: audit trail kho học được cho AI và điều tra sai lệch. Ảnh hưởng tới: giải thích chênh lệch tồn, tái hiện timeline thao tác; không thay thế financeledger. Bảng liên quan: products, productunits, users, stockdispatches, stockreceipts, warehouselocations (from/to). Đọc khi: UC6 (Manage inventory), UC10 (Dispatch — hậu kiểm biến động).$r23$),
        ('notifications', $r24$Thông báo in-app (loại, đã đọc, liên kết thực thể). Chức năng: đẩy sự kiện nghiệp vụ tới người dùng (duyệt, nhắc việc). Ảnh hưởng tới: trạng thái “đã xử lý chưa” trên UI, không là sổ sách kế toán. Bảng liên quan: users (CASCADE). Đọc khi: UC4 post-condition (nhân viên nhận thông báo sau phê duyệt), hộp thông báo chung.$r24$),
        ('storeprofiles', $r25$Hồ sơ cửa hàng theo Owner duy nhất (tên, MST, logo, liên hệ, mạng xã hội). Chức năng: branding POS/hóa đơn và thông tin pháp nhân hiển thị. Ảnh hưởng tới: in ấn, trải nghiệm POS, không trực tiếp thay đổi tồn hay giá. Bảng liên quan: users (owner_id CASCADE). Đọc khi: API Task073/074/075 (thiết lập cửa hàng), UC liên quan POS/bán lẻ khi cần hiển thị thương hiệu.$r25$),
        ('cashtransactions', $r26$Phiếu thu/chi thủ công (số tiền, danh mục, phương thức, trạng thái Pending/Completed, ngày, fund_id NOT NULL tới cash_funds theo V41). Chức năng: ghi nhận dòng tiền ngoài luồng đơn hàng, liên kết sổ cái khi hoàn tất. Ảnh hưởng tới: dòng tiền theo quỹ, đối soát với financeledger_id, báo cáo thu chi đa quỹ. Bảng liên quan: users (created_by RESTRICT), financeledger (SET NULL), cash_funds (fund_id). Đọc khi: module thu chi (Task064–068), báo cáo quỹ.$r26$),
        ('partnerdebts', $r27$Sổ công nợ đối tác (KH hoặc NCC, tổng nợ, đã trả, hạn, trạng thái InDebt/Cleared). Chức năng: theo dõi phải thu/phải trả tổng hợp ngoài chi tiết đơn/phiếu. Ảnh hưởng tới: chỉ số công nợ, aging, thanh khoản; remaining = total_amount - paid_amount (theo API). Bảng liên quan: customers hoặc suppliers (RESTRICT). Đọc khi: Task069–072, báo cáo tài chính/đối chiếu công nợ.$r27$),
        ('staffpasswordresetrequests', $r28$Yêu cầu reset mật khẩu nhân viên (message, Pending/Processed/Cancelled, người xử lý). Chức năng: quy trình Owner/Admin xử lý an toàn thay vì đổi pass trực tiếp trên user. Ảnh hưởng tới: khả năng đăng nhập lại của staff, audit processed_by/processed_at. Bảng liên quan: users (user_id CASCADE, processed_by SET NULL). Đọc khi: UC3 (Manage Staff Accounts), API Task004.$r28$),
        ('inventoryauditsessions', $r29$Phiên kiểm kê (mã, tiêu đề, ngày, trạng thái workflow, filter location/category, người tạo/hoàn tất). Chức năng: khung thời gian và phạm vi cho đợt đếm thực tế. Ảnh hưởng tới: kết quả điều chỉnh tồn sau khi hoàn tất, timeline sự kiện (inventory_audit_session_events). Bảng liên quan: users (created_by, completed_by), inventoryauditlines (CASCADE), inventory_audit_session_events. Đọc khi: Task021–028 (kiểm kê kho), UC6/kiểm soát tồn.$r29$),
        ('inventoryauditlines', $r30$Dòng kiểm kê theo inventory_id (SL hệ thống vs thực tế, đã đếm, variance_applied_at). Chức năng: ghi nhận lệch và thời điểm áp dụng điều chỉnh vào tồn. Ảnh hưởng tới: chênh lệch tồn, điều chỉnh kế toán kho nếu nghiệp vụ BE liên kết log điều chỉnh. Bảng liên quan: inventoryauditsessions (CASCADE), inventory (RESTRICT). Đọc khi: Task021–028, báo cáo kiểm kê chi tiết.$r30$),
        ('refresh_tokens', $r31$Bảng phiên refresh JWT (token hash, user_id, expires_at, metadata thiết bị nếu có). Chức năng: duy trì phiên đăng nhập an toàn và thu hồi/logout. Ảnh hưởng tới: bảo mật truy cập, không ảnh hưởng trực tiếp tồn hay doanh thu. Bảng liên quan: users (CASCADE). Đọc khi: luồng auth (Task001/003), mọi UC sau đăng nhập.$r31$),
        ('vouchers', $r32$Master mã khuyến mãi (giá trị/%, điều kiện, thời hạn, kênh POS/bán buôn). Chức năng: áp dụng giảm giá có kiểm soát trên đơn/POS. Ảnh hưởng tới: doanh thu thuần, margin sau khuyến mãi, và số lần dùng (join voucher_redemptions). Bảng liên quan: voucher_redemptions. Đọc khi: UC9 (Sales/POS — V19 walk-in/shift/voucher), báo cáo khuyến mãi.$r32$),
        ('voucher_redemptions', $r33$Lượt sử dụng voucher (liên kết đơn hoặc giao dịch bán lẻ, snapshot giá trị). Chức năng: chống dùng trùng và audit khuyến mãi thực tế. Ảnh hưởng tới: doanh thu sau giảm, đối soát với salesorders. Bảng liên quan: vouchers, salesorders (theo migration V24). Đọc khi: UC9/POS, Task092.$r33$),
        ('inventory_audit_session_events', $r34$Timeline sự kiện phiên kiểm kê (event_type, payload JSON, created_by). Chức năng: hiển thị lịch sử tạo/cập nhật/hủy/hoàn tất phiên. Ảnh hưởng tới: minh bạch quy trình kiểm kê, không trực tiếp là sổ tồn. Bảng liên quan: inventoryauditsessions (session_id), users. Đọc khi: UI timeline kiểm kê (V12), Task021–028.$r34$),
        ('stockdispatch_lines', $r35$Dòng chi tiết phiếu xuất (dispatch_id, inventory_id, quantity, unit_price_snapshot khi lập từ đơn). Chức năng: chỉ định trừ từ lô/vị trí cụ thể trong inventory; join đúng: dispatch_id → stockdispatches.id rồi stockdispatches.order_id → salesorders.id (không join dispatch_id với salesorders.id). Ảnh hưởng tới: SL xuất thực tế, snapshot giá dòng, tồn sau xuất. Bảng liên quan: stockdispatches (CASCADE), inventory (RESTRICT — suy ra products/lot/location). Xóa mềm nằm ở header stockdispatches (deleted_at) theo V35. Đọc khi: UC10, báo cáo xuất chi tiết (V35–V36).$r35$),
        ('cash_funds', $r36$Danh mục quỹ tiền (tiền mặt, TK NH…) làm dimension cho thu chi và sổ cái. Chức năng: phân tách dòng tiền theo quỹ, mặc định giao dịch/ledger. Ảnh hưởng tới: số dư theo quỹ, đối soát cashtransactions và financeledger (fund_id). Bảng liên quan: cashtransactions, financeledger (theo V41). Đọc khi: module quỹ/thu chi, báo cáo dòng tiền đa quỹ.$r36$),
        ('ai_table_description', $r37$Registry meta: một dòng / tên bảng vật lý PostgreSQL (lowercase) mô tả nghiệp vụ cho prompt AI và join SchemaArtifact/YAML introspection. Chức năng: bối cảnh ngữ nghĩa cho text-to-SQL và merge schema. Ảnh hưởng tới: chất lượng câu trả lời AI, không phải dữ liệu ERP vận hành. Bảng liên quan: ai_column_description (FK table_name CASCADE). Đọc khi: pipeline AI Python merge mô tả bảng, Task103.$r37$),
        ('ai_column_description', $r38$Registry meta theo cặp (table_name, column_name) mô tả nghiệp vụ cột cho AI (merge ColumnMeta / format_schema_block). Chức năng: giảm join sai kiểu (đã có V46 gợi ý dispatch_id). Ảnh hưởng tới: độ chính xác SQL sinh ra, không ảnh hưởng sổ sách. Bảng liên quan: ai_table_description (FK ON DELETE CASCADE), information_schema.columns (theo tên vật lý). Đọc khi: Task103 consumer cột, đồng bộ introspection DB.$r38$)
) AS v(table_name, description)
WHERE t.table_name = v.table_name;
