-- Task103 — Làm giàu mô tả cột trong ai_column_description (V45 ngắn/mơ hồ; V46 chỉ dispatch join).
-- Nguồn schema: V1 baseline + V5–V48 (cột mới, CHECK, soft-delete). Consumer: ai_python merge ColumnMeta (max ~320 ký tự/cột).
-- Idempotent: INSERT cột thiếu; UPDATE ghi đè description + updated_at.

-- ---------------------------------------------------------------------------
-- Cột chưa có trong seed V45 (migration V5–V41)
-- ---------------------------------------------------------------------------
INSERT INTO ai_column_description (table_name, column_name, description)
SELECT v.table_name, v.column_name, v.description
FROM (
    VALUES
        ('users', 'staff_code',
         'Mã nhân viên hiển thị (unique khi NOT NULL, V5). Đọc khi: tra cứu NV theo mã thay vì username; không dùng thay users.id cho join FK.'),
        ('categories', 'deleted_at',
         'Xóa mềm danh mục (TIMESTAMPTZ, V14). Lọc báo cáo/catalog: WHERE deleted_at IS NULL. category_code unique chỉ trên bản ghi còn hiệu lực.'),
        ('customers', 'deleted_at',
         'Xóa mềm khách (V38). Báo cáo/KPI bán: WHERE deleted_at IS NULL. Mã KH unique trên bản ghi active; đơn cũ vẫn giữ customer_id.'),
        ('inventory', 'unit_id',
         'FK productunits.id — đơn vị hiển thị/ghi nhận meta (V7). quantity luôn theo đơn vị cơ sở; quy đổi qua productunits.conversion_rate.'),
        ('cashtransactions', 'performed_by',
         'FK users.id — nhân viên thực hiện thu/chi (V25, NOT NULL). Khác created_by khi Owner lập hộ; PATCH cập nhật user hiện tại.'),
        ('partnerdebts', 'created_by',
         'FK users.id — người lập công nợ (V26, NOT NULL). Audit phải thu/trả; không thay partner_type/customer_id/supplier_id.'),
        ('inventoryauditsessions', 'cancel_reason',
         'Lý do hủy phiên kiểm kê (V11, tối đa 1000 ký tự). Chỉ có ý nghĩa khi status = Cancelled; đọc khi tra timeline hủy đợt kiểm.'),
        ('storeprofiles', 'default_retail_location_id',
         'FK warehouselocations.id — kho/vị trí mặc định trừ tồn POS bán lẻ (V20, SET NULL). NULL = chưa cấu hình; join tồn qua inventory.location_id.')
) AS v(table_name, column_name, description)
WHERE EXISTS (SELECT 1 FROM ai_table_description t WHERE t.table_name = v.table_name)
  AND NOT EXISTS (
        SELECT 1 FROM ai_column_description c
        WHERE c.table_name = v.table_name AND c.column_name = v.column_name
    );

-- ---------------------------------------------------------------------------
-- Cập nhật mô tả chi tiết (ghi đè V45/V46)
-- ---------------------------------------------------------------------------
UPDATE ai_column_description AS c
SET description = v.description,
    updated_at  = CURRENT_TIMESTAMP
FROM (
    VALUES
        -- roles
        ('roles', 'id', 'PK serial vai trò. Tham chiếu từ users.role_id (RESTRICT). Không lọc nghiệp vụ kho/bán trực tiếp.'),
        ('roles', 'name', 'Tên vai trò duy nhất: Owner | Staff | Admin. Đọc khi: phân quyền menu/thao tác; join users để biết nhóm quyền.'),
        ('roles', 'permissions', 'JSONB ma trận quyền (menu, can_approve, can_view_system_logs…). Đọc khi: giải thích quyền cụ thể — parse JSON, không hard-code tên cột con.'),
        ('roles', 'created_at', 'Thời điểm tạo vai trò; ít dùng báo cáo vận hành.'),

        -- categories
        ('categories', 'id', 'PK danh mục. FK: products.category_id, categories.parent_id (cây).'),
        ('categories', 'category_code', 'Mã danh mục duy nhất trên bản ghi chưa xóa mềm (partial unique V14). Dùng tra cứu nhanh, không thay id khi join.'),
        ('categories', 'name', 'Tên hiển thị danh mục. GROUP BY / lọc báo cáo theo nhóm hàng qua join products.category_id.'),
        ('categories', 'description', 'Mô tả dài tùy chọn; không ảnh hưởng tồn hay giá.'),
        ('categories', 'parent_id', 'FK categories.id — danh mục cha (cây). NULL = gốc. ON DELETE SET NULL. Đọc khi: phân cấp nhóm hàng.'),
        ('categories', 'sort_order', 'Thứ tự hiển thị UI (số nhỏ trước). Không ảnh hưởng giá trị tồn.'),
        ('categories', 'status', 'CHECK: Active | Inactive. Lọc catalog: status = Active AND deleted_at IS NULL.'),
        ('categories', 'created_at', 'Thời điểm tạo danh mục; audit catalog.'),
        ('categories', 'updated_at', 'Cập nhật metadata danh mục gần nhất.'),

        -- suppliers
        ('suppliers', 'id', 'PK nhà cung cấp. FK: stockreceipts.supplier_id, partnerdebts.supplier_id (RESTRICT).'),
        ('suppliers', 'supplier_code', 'Mã NCC duy nhất (vd. NCC0001). Tra cứu thay id khi người dùng nhập mã.'),
        ('suppliers', 'name', 'Tên NCC. LIKE/ILIKE tìm kiếm; GROUP BY báo cáo mua hàng.'),
        ('suppliers', 'contact_person', 'Tên người liên hệ; không join nghiệp vụ.'),
        ('suppliers', 'phone', 'Số điện thoại NCC; index tìm nhanh.'),
        ('suppliers', 'email', 'Email NCC tùy chọn.'),
        ('suppliers', 'address', 'Địa chỉ NCC.'),
        ('suppliers', 'tax_code', 'Mã số thuế NCC; đối chiếu hóa đơn.'),
        ('suppliers', 'status', 'CHECK: Active | Inactive. Chỉ chọn NCC Active khi lập phiếu nhập mới.'),
        ('suppliers', 'created_at', 'Thời điểm tạo master NCC.'),
        ('suppliers', 'updated_at', 'Cập nhật thông tin NCC gần nhất.'),

        -- customers
        ('customers', 'id', 'PK khách. FK: salesorders.customer_id, partnerdebts.customer_id (RESTRICT). Walk-in: customer_code = WALKIN.'),
        ('customers', 'customer_code', 'Mã KH duy nhất (active). WALKIN = khách lẻ POS. Lọc: deleted_at IS NULL.'),
        ('customers', 'name', 'Tên khách/tổ chức. GROUP BY doanh thu: join salesorders ON customer_id.'),
        ('customers', 'phone', 'SĐT bắt buộc, unique index; tra cứu KH tại quầy.'),
        ('customers', 'email', 'Email tùy chọn.'),
        ('customers', 'address', 'Địa chỉ KH; khác shipping_address trên đơn.'),
        ('customers', 'loyalty_points', 'Điểm tích lũy tích lũy (INT). Không tự trừ khi bán — cập nhật theo nghiệp vụ BE.'),
        ('customers', 'status', 'CHECK: Active | Inactive. Kết hợp deleted_at IS NULL cho danh sách bán.'),
        ('customers', 'created_at', 'Thời điểm tạo KH.'),
        ('customers', 'updated_at', 'Cập nhật hồ sơ KH.'),

        -- warehouselocations
        ('warehouselocations', 'id', 'PK vị trí kho. FK: inventory.location_id, inventorylogs from/to, storeprofiles.default_retail_location_id.'),
        ('warehouselocations', 'warehouse_code', 'Mã kho (vd. WH01). Unique cặp với shelf_code.'),
        ('warehouselocations', 'shelf_code', 'Mã kệ/vị trí trong kho. Unique (warehouse_code, shelf_code).'),
        ('warehouselocations', 'description', 'Mô tả vị trí; hiển thị UI.'),
        ('warehouselocations', 'capacity', 'Sức chứa ước tính (DECIMAL); tham khảo, không chặn nhập tồn.'),
        ('warehouselocations', 'status', 'CHECK: Active | Maintenance | Inactive. Chỉ Active cho nhập/xuất mới.'),
        ('warehouselocations', 'created_at', 'Tạo vị trí kho.'),

        -- users
        ('users', 'id', 'PK user nội bộ. Khóa audit: staff_id, approved_by, user_id, created_by trên hầu hết chứng từ.'),
        ('users', 'username', 'Đăng nhập duy nhất; không dùng join báo cáo — ưu tiên id hoặc staff_code.'),
        ('users', 'password_hash', 'Hash bcrypt/argon2 — không SELECT trong báo cáo AI.'),
        ('users', 'full_name', 'Họ tên hiển thị trên phiếu/audit.'),
        ('users', 'email', 'Email đăng nhập duy nhất.'),
        ('users', 'phone', 'SĐT nhân viên tùy chọn.'),
        ('users', 'role_id', 'FK roles.id (RESTRICT). Join roles để biết quyền Owner/Staff/Admin.'),
        ('users', 'status', 'CHECK: Active | Locked. Locked = không đăng nhập; vẫn giữ FK lịch sử.'),
        ('users', 'last_login', 'Đăng nhập gần nhất; audit bảo mật, không phải ngày chứng từ.'),
        ('users', 'created_at', 'Tạo tài khoản.'),
        ('users', 'updated_at', 'Sửa hồ sơ user.'),

        -- products
        ('products', 'id', 'PK sản phẩm. Hub join: inventory, orderdetails, stockreceiptdetails, inventorylogs.'),
        ('products', 'category_id', 'FK categories.id (SET NULL khi xóa DM). Lọc hàng theo nhóm.'),
        ('products', 'sku_code', 'Mã SKU duy nhất — cột tra cứu chính khi user nói mã hàng.'),
        ('products', 'barcode', 'Mã vạch quét POS; unique index.'),
        ('products', 'name', 'Tên sản phẩm; ILIKE tìm kiếm catalog.'),
        ('products', 'image_url', 'URL ảnh đại diện (legacy); chi tiết ảnh ở productimages.'),
        ('products', 'description', 'Mô tả dài; không ảnh hưởng tồn.'),
        ('products', 'weight', 'Khối lượng gram (DECIMAL); logistics, không quy đổi đơn vị bán.'),
        ('products', 'status', 'CHECK: Active | Inactive. Inactive: không bán mới, tồn cũ vẫn có thể.'),
        ('products', 'created_at', 'Tạo SKU.'),
        ('products', 'updated_at', 'Sửa master sản phẩm.'),

        -- productimages
        ('productimages', 'id', 'PK ảnh phụ.'),
        ('productimages', 'product_id', 'FK products.id CASCADE. Join ảnh theo SKU qua products.id.'),
        ('productimages', 'image_url', 'URL Cloudinary/CDN; không chứa số lượng tồn.'),
        ('productimages', 'alt_text', 'Alt SEO/accessibility.'),
        ('productimages', 'is_primary', 'BOOLEAN — đúng một ảnh primary/SKU (unique index V15).'),
        ('productimages', 'sort_order', 'Thứ tự carousel (nhỏ trước).'),
        ('productimages', 'file_size_bytes', 'Kích thước file bytes.'),
        ('productimages', 'mime_type', 'MIME (image/jpeg…).'),
        ('productimages', 'created_at', 'Upload ảnh.'),

        -- alertsettings
        ('alertsettings', 'id', 'PK cấu hình cảnh báo.'),
        ('alertsettings', 'owner_id', 'FK users.id CASCADE — chủ cấu hình (thường Owner).'),
        ('alertsettings', 'alert_type', 'CHECK: LowStock | ExpiryDate | HighValueTransaction | PendingApproval | PartnerDebtDueSoon.'),
        ('alertsettings', 'threshold_value', 'Ngưỡng số (tồn tối thiểu, ngày hết hạn… tùy alert_type).'),
        ('alertsettings', 'channel', 'CHECK: App | Email | SMS | Zalo — kênh gửi.'),
        ('alertsettings', 'frequency', 'CHECK: Realtime | Daily | Weekly.'),
        ('alertsettings', 'is_enabled', 'Bật/tắt rule; false = không kích hoạt.'),
        ('alertsettings', 'recipients', 'JSONB danh sách nhận thêm (email/phone).'),
        ('alertsettings', 'created_at', 'Tạo rule.'),
        ('alertsettings', 'updated_at', 'Sửa rule.'),

        -- systemlogs
        ('systemlogs', 'id', 'PK log audit.'),
        ('systemlogs', 'log_level', 'CHECK: INFO | WARNING | ERROR | CRITICAL.'),
        ('systemlogs', 'module', 'Module nguồn (Auth, Inventory…).'),
        ('systemlogs', 'action', 'Hành động (CREATE, APPROVE…).'),
        ('systemlogs', 'user_id', 'FK users.id SET NULL — actor; NULL = hệ thống.'),
        ('systemlogs', 'message', 'Nội dung log text.'),
        ('systemlogs', 'stack_trace', 'Stack trace khi lỗi; thường NULL.'),
        ('systemlogs', 'context_data', 'JSONB payload bổ sung (entity id, diff…).'),
        ('systemlogs', 'created_at', 'Thời điểm ghi log — cột thời gian chính khi lọc audit.'),

        -- financeledger
        ('financeledger', 'id', 'PK bút toán sổ cái.'),
        ('financeledger', 'transaction_date', 'Ngày chứng từ kế toán (DATE) — ưu tiên lọc báo cáo tài chính theo cột này.'),
        ('financeledger', 'transaction_type', 'CHECK: SalesRevenue | PurchaseCost | OperatingExpense | Refund — loại bút toán.'),
        ('financeledger', 'reference_type', 'Loại chứng từ nguồn (StockReceipt, CashTransaction…) — đa hình.'),
        ('financeledger', 'reference_id', 'ID chứng từ nguồn (cùng reference_type); không join mù sang bảng khác.'),
        ('financeledger', 'amount', 'Số tiền bút toán (DECIMAL); quy ước dương/âm theo loại — đọc SRS kế toán.'),
        ('financeledger', 'description', 'Diễn giải bút toán.'),
        ('financeledger', 'created_by', 'FK users.id RESTRICT — người lập.'),
        ('financeledger', 'created_at', 'Thời điểm ghi sổ (timestamp).'),
        ('financeledger', 'updated_at', 'Sửa bút toán (hiếm).'),
        ('financeledger', 'fund_id', 'FK cash_funds.id NOT NULL (V41) — quỹ ghi nhận. GROUP BY quỹ khi báo cáo.'),

        -- aiinsights / aichathistory / mediaaudits (legacy AI)
        ('aiinsights', 'id', 'PK insight AI đã lưu.'),
        ('aiinsights', 'owner_id', 'FK users.id CASCADE.'),
        ('aiinsights', 'dashboard_snapshot', 'JSON snapshot KPI lúc sinh insight — không thay financeledger.'),
        ('aiinsights', 'prompt', 'Prompt gửi LLM.'),
        ('aiinsights', 'ai_advice', 'Kết quả markdown gợi ý.'),
        ('aiinsights', 'model_used', 'Tên model LLM.'),
        ('aiinsights', 'tokens_used', 'Token tiêu thụ.'),
        ('aiinsights', 'created_at', 'Thời điểm tạo insight.'),
        ('aichathistory', 'id', 'PK tin nhắn chat.'),
        ('aichathistory', 'user_id', 'FK users.id CASCADE.'),
        ('aichathistory', 'session_id', 'UUID/string phiên — GROUP BY hội thoại.'),
        ('aichathistory', 'message', 'Nội dung User/Bot (có thể redact PII).'),
        ('aichathistory', 'sender', 'CHECK: User | Bot.'),
        ('aichathistory', 'intent', 'JSON intent đã nhận dạng (debug).'),
        ('aichathistory', 'response_time_ms', 'Độ trễ ms.'),
        ('aichathistory', 'created_at', 'Thời điểm tin nhắn.'),
        ('mediaaudits', 'id', 'PK audit file.'),
        ('mediaaudits', 'file_type', 'CHECK: OCR_Image | Voice_Audio.'),
        ('mediaaudits', 'cloud_url', 'URL file cloud.'),
        ('mediaaudits', 'entity_type', 'Tên loại thực thể (polymorphic) — đọc cùng entity_id.'),
        ('mediaaudits', 'entity_id', 'ID thực thể gắn file; không join trực tiếp nếu không biết entity_type.'),
        ('mediaaudits', 'file_size_bytes', 'Kích thước bytes.'),
        ('mediaaudits', 'mime_type', 'MIME file.'),
        ('mediaaudits', 'uploaded_by', 'FK users.id SET NULL.'),
        ('mediaaudits', 'created_at', 'Thời điểm upload.'),

        -- productunits / productpricehistory
        ('productunits', 'id', 'PK đơn vị quy đổi. FK: orderdetails.unit_id, stockreceiptdetails.unit_id, inventory.unit_id.'),
        ('productunits', 'product_id', 'FK products.id CASCADE — mỗi SKU có nhiều đơn vị.'),
        ('productunits', 'unit_name', 'Tên đơn vị (Thùng, Lon, Cái…).'),
        ('productunits', 'conversion_rate', 'Hệ số quy đổi về đơn vị cơ sở (>0). SL tồn inventory luôn base unit.'),
        ('productunits', 'is_base_unit', 'BOOLEAN — một base unit/SKU. Dùng xác định đơn vị chuẩn tồn.'),
        ('productunits', 'created_at', 'Tạo đơn vị.'),
        ('productunits', 'updated_at', 'Sửa hệ số quy đổi.'),
        ('productpricehistory', 'id', 'PK lịch sử giá.'),
        ('productpricehistory', 'product_id', 'FK products.id.'),
        ('productpricehistory', 'unit_id', 'FK productunits.id — giá theo đơn vị bán.'),
        ('productpricehistory', 'cost_price', 'Giá vốn tại effective_date (>=0).'),
        ('productpricehistory', 'sale_price', 'Giá bán niêm yết tại effective_date.'),
        ('productpricehistory', 'effective_date', 'Ngày hiệu lực; lấy bản ghi mới nhất: ORDER BY effective_date DESC.'),
        ('productpricehistory', 'created_at', 'Thời điểm insert lịch sử.'),

        -- inventory
        ('inventory', 'id', 'PK lô tồn. FK: stockdispatch_lines.inventory_id, inventoryauditlines.inventory_id (RESTRICT).'),
        ('inventory', 'product_id', 'FK products.id RESTRICT. Join SKU: inventory → products.'),
        ('inventory', 'location_id', 'FK warehouselocations.id RESTRICT. Tồn theo vị trí vật lý.'),
        ('inventory', 'batch_number', 'Số lô; unique logic với product+location. NULL = không quản lô.'),
        ('inventory', 'expiry_date', 'Hạn dùng (DATE); lọc cận date, alert ExpiryDate.'),
        ('inventory', 'quantity', 'Số lượng tồn đơn vị cơ sở (INT >=0) — nguồn sự thật tồn.'),
        ('inventory', 'min_quantity', 'Ngưỡng cảnh báo tồn tối thiểu trên lô.'),
        ('inventory', 'updated_at', 'Cập nhật khi biến động tồn; xem inventorylogs cho timeline chi tiết.'),

        -- stockreceipts
        ('stockreceipts', 'id', 'PK phiếu nhập. FK: stockreceiptdetails.receipt_id, inventorylogs.receipt_id.'),
        ('stockreceipts', 'receipt_code', 'Mã phiếu duy nhất (PN-…). Tra cứu thay id.'),
        ('stockreceipts', 'supplier_id', 'FK suppliers.id RESTRICT.'),
        ('stockreceipts', 'staff_id', 'FK users.id — nhân viên lập phiếu.'),
        ('stockreceipts', 'receipt_date', 'Ngày nhập (DATE) — cột thời gian nghiệp vụ chính khi báo cáo mua.'),
        ('stockreceipts', 'status', 'CHECK: Draft | Pending | Approved | Rejected. Chỉ Approved mới cộng tồn + ledger.'),
        ('stockreceipts', 'invoice_number', 'Số hóa đơn NCC.'),
        ('stockreceipts', 'total_amount', 'Tổng tiền phiếu (>=0); có thể khác SUM chi tiết nếu làm tròn.'),
        ('stockreceipts', 'notes', 'Ghi chú phiếu.'),
        ('stockreceipts', 'approved_by', 'FK users.id SET NULL — người duyệt khi Approved.'),
        ('stockreceipts', 'approved_at', 'Thời điểm duyệt; NULL nếu chưa Approved.'),
        ('stockreceipts', 'created_at', 'Tạo phiếu (timestamp).'),
        ('stockreceipts', 'updated_at', 'Sửa header phiếu.'),

        -- salesorders
        ('salesorders', 'id', 'PK đơn bán. FK: orderdetails, stockdispatches.order_id, voucher_redemptions.'),
        ('salesorders', 'order_code', 'Mã đơn duy nhất (SO-…).'),
        ('salesorders', 'customer_id', 'FK customers.id RESTRICT. Walk-in: customers.customer_code = WALKIN.'),
        ('salesorders', 'user_id', 'FK users.id RESTRICT — nhân viên tạo đơn.'),
        ('salesorders', 'total_amount', 'Tổng tiền hàng trước chiết khấu đơn (>=0).'),
        ('salesorders', 'discount_amount', 'Tổng giảm giá đơn (>=0); voucher có thể nằm trong này.'),
        ('salesorders', 'final_amount', 'GENERATED STORED: total_amount - discount_amount. Dùng SUM doanh thu thuần.'),
        ('salesorders', 'status', 'CHECK: Pending | Processing | Partial | Shipped | Delivered | Cancelled — vòng đời giao hàng.'),
        ('salesorders', 'parent_order_id', 'FK salesorders.id — đơn con backorder khi thiếu hàng.'),
        ('salesorders', 'shipping_address', 'Địa chỉ giao; có thể khác customers.address.'),
        ('salesorders', 'notes', 'Ghi chú đơn.'),
        ('salesorders', 'created_at', 'Thời điểm tạo đơn — lọc doanh thu theo ngày bán.'),
        ('salesorders', 'updated_at', 'Cập nhật trạng thái đơn.'),
        ('salesorders', 'cancelled_at', 'Thời điểm hủy; NULL nếu chưa hủy.'),
        ('salesorders', 'cancelled_by', 'FK users.id SET NULL — người hủy.'),
        ('salesorders', 'order_channel', 'CHECK: Retail | Wholesale | Return — kênh bán; KPI theo kênh.'),
        ('salesorders', 'payment_status', 'CHECK: Paid | Unpaid | Partial — thanh toán, khác status giao hàng.'),
        ('salesorders', 'ref_sales_order_id', 'FK salesorders.id — đơn tham chiếu (đổi/trả).'),
        ('salesorders', 'voucher_id', 'FK vouchers.id SET NULL — mã giảm áp dụng (V19).'),
        ('salesorders', 'pos_shift_ref', 'Mã ca POS (V19); nhóm giao dịch lẻ theo ca.'),

        -- stockreceiptdetails
        ('stockreceiptdetails', 'id', 'PK dòng nhập.'),
        ('stockreceiptdetails', 'receipt_id', 'FK stockreceipts.id CASCADE — join header phiếu nhập.'),
        ('stockreceiptdetails', 'product_id', 'FK products.id RESTRICT.'),
        ('stockreceiptdetails', 'unit_id', 'FK productunits.id RESTRICT — đơn vị nhập; quy đổi ra base cho tồn.'),
        ('stockreceiptdetails', 'quantity', 'SL nhập (>0) theo unit_id.'),
        ('stockreceiptdetails', 'cost_price', 'Đơn giá vốn dòng (>=0).'),
        ('stockreceiptdetails', 'batch_number', 'Số lô nhập; unique với receipt+product.'),
        ('stockreceiptdetails', 'expiry_date', 'Hạn dùng lô nhập.'),
        ('stockreceiptdetails', 'line_total', 'GENERATED: quantity * cost_price. SUM cho giá trị dòng nhập.'),
        ('stockreceiptdetails', 'created_at', 'Tạo dòng.'),

        -- orderdetails
        ('orderdetails', 'id', 'PK dòng đơn.'),
        ('orderdetails', 'order_id', 'FK salesorders.id CASCADE.'),
        ('orderdetails', 'product_id', 'FK products.id RESTRICT.'),
        ('orderdetails', 'unit_id', 'FK productunits.id RESTRICT.'),
        ('orderdetails', 'quantity', 'SL đặt (>0) theo unit_id.'),
        ('orderdetails', 'price_at_time', 'Đơn giá snapshot lúc bán (>=0); không đổi khi giá master đổi.'),
        ('orderdetails', 'line_total', 'GENERATED: quantity * price_at_time.'),
        ('orderdetails', 'dispatched_qty', 'SL đã xuất (0..quantity). =quantity đủ hàng; <quantity cần backorder. Xuất thực tế: stockdispatches → stockdispatch_lines.'),
        ('orderdetails', 'created_at', 'Tạo dòng đơn.'),

        -- stockdispatches (V46 giữ join hint trên order_id)
        ('stockdispatches', 'id', 'PK phiếu xuất. FK: stockdispatch_lines.dispatch_id, inventorylogs.dispatch_id.'),
        ('stockdispatches', 'dispatch_code', 'Mã phiếu xuất (PX-…).'),
        ('stockdispatches', 'order_id',
         'FK salesorders.id (đơn nguồn, NULL được — xuất tay V32). Chuỗi tới dòng xuất: salesorders → stockdispatches → stockdispatch_lines; không join order_id = dispatch_id.'),
        ('stockdispatches', 'user_id', 'FK users.id — người lập/xử lý phiếu xuất.'),
        ('stockdispatches', 'dispatch_date', 'Ngày xuất (DATE) — lọc báo cáo xuất kho.'),
        ('stockdispatches', 'status',
         'CHECK (V36): Pending | Full | Partial | Cancelled | WaitingDispatch | Delivering | Delivered. Lọc phiếu active: deleted_at IS NULL.'),
        ('stockdispatches', 'notes', 'Ghi chú phiếu xuất.'),
        ('stockdispatches', 'created_at', 'Tạo phiếu.'),
        ('stockdispatches', 'updated_at', 'Cập nhật trạng thái xuất.'),
        ('stockdispatches', 'reference_label', 'Nhãn mô tả khi order_id NULL (xuất tay/điều chỉnh).'),
        ('stockdispatches', 'deleted_at', 'Xóa mềm phiếu (V35). Báo cáo: WHERE deleted_at IS NULL.'),
        ('stockdispatches', 'deleted_by_user_id', 'FK users.id — người xóa mềm.'),
        ('stockdispatches', 'delete_reason', 'Lý do xóa mềm (text).'),

        -- inventorylogs
        ('inventorylogs', 'id', 'PK biến động tồn.'),
        ('inventorylogs', 'product_id', 'FK products.id RESTRICT.'),
        ('inventorylogs', 'action_type', 'CHECK: INBOUND | OUTBOUND | TRANSFER | ADJUSTMENT.'),
        ('inventorylogs', 'quantity_change', 'Biến động SL (+ nhập, - xuất) theo base unit.'),
        ('inventorylogs', 'unit_id', 'FK productunits.id — đơn vị ghi nhận trên log.'),
        ('inventorylogs', 'user_id', 'FK users.id SET NULL — thao tác viên.'),
        ('inventorylogs', 'dispatch_id', 'FK stockdispatches.id — liên kết phiếu xuất OUTBOUND.'),
        ('inventorylogs', 'receipt_id', 'FK stockreceipts.id — liên kết phiếu nhập INBOUND.'),
        ('inventorylogs', 'from_location_id', 'FK warehouselocations.id — vị trí nguồn (TRANSFER/OUTBOUND).'),
        ('inventorylogs', 'to_location_id', 'FK warehouselocations.id — vị trí đích (TRANSFER/INBOUND).'),
        ('inventorylogs', 'reference_note', 'Ghi chú tham chiếu tự do.'),
        ('inventorylogs', 'created_at', 'Thời điểm biến động — timeline kho.'),

        -- notifications
        ('notifications', 'id', 'PK thông báo in-app.'),
        ('notifications', 'user_id', 'FK users.id CASCADE — người nhận.'),
        ('notifications', 'notification_type',
         'CHECK (V39): ApprovalResult | LowStock | ExpiryWarning | SystemAlert | PasswordResetRequest | StockReceiptPendingApproval | StockDispatchPendingApproval | StockDispatchShortage.'),
        ('notifications', 'title', 'Tiêu đề ngắn.'),
        ('notifications', 'message', 'Nội dung thông báo.'),
        ('notifications', 'is_read', 'BOOLEAN đã đọc.'),
        ('notifications', 'reference_type', 'Loại entity liên kết (polymorphic).'),
        ('notifications', 'reference_id', 'ID entity liên kết; đọc cùng reference_type.'),
        ('notifications', 'created_at', 'Tạo thông báo.'),
        ('notifications', 'read_at', 'Thời điểm đánh dấu đã đọc; NULL = chưa đọc.'),

        -- storeprofiles
        ('storeprofiles', 'id', 'PK hồ sơ cửa hàng (1 Owner).'),
        ('storeprofiles', 'owner_id', 'FK users.id CASCADE UNIQUE — Owner sở hữu.'),
        ('storeprofiles', 'name', 'Tên cửa hàng in bill/POS.'),
        ('storeprofiles', 'business_category', 'Ngành hàng kinh doanh.'),
        ('storeprofiles', 'address', 'Địa chỉ cửa hàng.'),
        ('storeprofiles', 'phone', 'SĐT cửa hàng.'),
        ('storeprofiles', 'email', 'Email cửa hàng.'),
        ('storeprofiles', 'website', 'Website.'),
        ('storeprofiles', 'tax_code', 'MST trên hóa đơn.'),
        ('storeprofiles', 'footer_note', 'Chân bill in POS.'),
        ('storeprofiles', 'logo_url', 'URL logo.'),
        ('storeprofiles', 'facebook_url', 'Link Facebook.'),
        ('storeprofiles', 'instagram_handle', 'Handle Instagram.'),
        ('storeprofiles', 'created_at', 'Tạo hồ sơ.'),
        ('storeprofiles', 'updated_at', 'Sửa hồ sơ.'),

        -- cashtransactions
        ('cashtransactions', 'id', 'PK phiếu thu/chi.'),
        ('cashtransactions', 'transaction_code', 'Mã giao dịch duy nhất.'),
        ('cashtransactions', 'direction', 'CHECK: Income | Expense.'),
        ('cashtransactions', 'amount', 'Số tiền dương (>0); chiều Income/Expense quyết định thu hay chi.'),
        ('cashtransactions', 'category', 'Danh mục thu chi (text).'),
        ('cashtransactions', 'description', 'Diễn giải phiếu.'),
        ('cashtransactions', 'payment_method', 'Tiền mặt, chuyển khoản… (text).'),
        ('cashtransactions', 'status', 'CHECK: Pending | Completed | Cancelled. Completed mới gắn finance_ledger_id.'),
        ('cashtransactions', 'transaction_date', 'Ngày chứng từ thu chi.'),
        ('cashtransactions', 'finance_ledger_id', 'FK financeledger.id SET NULL — bút toán sau hoàn tất.'),
        ('cashtransactions', 'created_by', 'FK users.id RESTRICT — người tạo phiếu.'),
        ('cashtransactions', 'created_at', 'Tạo phiếu.'),
        ('cashtransactions', 'updated_at', 'Sửa phiếu.'),
        ('cashtransactions', 'fund_id', 'FK cash_funds.id NOT NULL (V41) — quỹ thu/chi.'),

        -- partnerdebts
        ('partnerdebts', 'id', 'PK công nợ.'),
        ('partnerdebts', 'debt_code', 'Mã công nợ duy nhất.'),
        ('partnerdebts', 'partner_type', 'CHECK: Customer | Supplier — xác định cột FK nào dùng.'),
        ('partnerdebts', 'customer_id', 'FK customers.id khi partner_type=Customer; NULL nếu Supplier.'),
        ('partnerdebts', 'supplier_id', 'FK suppliers.id khi partner_type=Supplier; NULL nếu Customer.'),
        ('partnerdebts', 'total_amount', 'Tổng phải thu/chi (>=0).'),
        ('partnerdebts', 'paid_amount', 'Đã thanh toán (<= total_amount). Còn lại: total_amount - paid_amount.'),
        ('partnerdebts', 'due_date', 'Hạn thanh toán (DATE).'),
        ('partnerdebts', 'status', 'CHECK: InDebt | Cleared.'),
        ('partnerdebts', 'notes', 'Ghi chú công nợ.'),
        ('partnerdebts', 'created_at', 'Tạo sổ công nợ.'),
        ('partnerdebts', 'updated_at', 'Cập nhật thanh toán.'),

        -- staffpasswordresetrequests
        ('staffpasswordresetrequests', 'id', 'PK yêu cầu reset.'),
        ('staffpasswordresetrequests', 'user_id', 'FK users.id CASCADE — nhân viên cần reset.'),
        ('staffpasswordresetrequests', 'message', 'Nội dung yêu cầu từ staff.'),
        ('staffpasswordresetrequests', 'status', 'CHECK: Pending | Processed | Cancelled.'),
        ('staffpasswordresetrequests', 'processed_by', 'FK users.id SET NULL — Owner/Admin xử lý.'),
        ('staffpasswordresetrequests', 'created_at', 'Gửi yêu cầu.'),
        ('staffpasswordresetrequests', 'processed_at', 'Xử lý xong; NULL nếu Pending.'),

        -- inventoryauditsessions / lines / events
        ('inventoryauditsessions', 'id', 'PK phiên kiểm kê.'),
        ('inventoryauditsessions', 'audit_code', 'Mã phiên duy nhất.'),
        ('inventoryauditsessions', 'title', 'Tiêu đề phiên.'),
        ('inventoryauditsessions', 'audit_date', 'Ngày kiểm (DATE).'),
        ('inventoryauditsessions', 'status',
         'CHECK (V12): Pending | In Progress | Pending Owner Approval | Completed | Cancelled | Re-check.'),
        ('inventoryauditsessions', 'location_filter', 'Lọc phạm vi theo vị trí kho (text/ids tùy BE).'),
        ('inventoryauditsessions', 'category_filter', 'Lọc phạm vi theo danh mục.'),
        ('inventoryauditsessions', 'notes', 'Ghi chú phiên.'),
        ('inventoryauditsessions', 'created_by', 'FK users.id — người tạo phiên.'),
        ('inventoryauditsessions', 'completed_at', 'Hoàn tất phiên; NULL khi chưa xong.'),
        ('inventoryauditsessions', 'completed_by', 'FK users.id SET NULL — người hoàn tất.'),
        ('inventoryauditsessions', 'created_at', 'Tạo phiên.'),
        ('inventoryauditsessions', 'updated_at', 'Cập nhật phiên.'),
        ('inventoryauditsessions', 'deleted_at', 'Xóa mềm phiên (V12). Lọc: deleted_at IS NULL.'),
        ('inventoryauditsessions', 'owner_notes', 'Ghi chú Owner khi phê duyệt/hủy.'),
        ('inventoryauditlines', 'id', 'PK dòng kiểm.'),
        ('inventoryauditlines', 'session_id', 'FK inventoryauditsessions.id CASCADE.'),
        ('inventoryauditlines', 'inventory_id', 'FK inventory.id RESTRICT — lô đang kiểm.'),
        ('inventoryauditlines', 'system_quantity', 'SL tồn hệ thống tại thời điểm kiểm.'),
        ('inventoryauditlines', 'actual_quantity', 'SL đếm thực tế.'),
        ('inventoryauditlines', 'is_counted', 'BOOLEAN đã đếm dòng này.'),
        ('inventoryauditlines', 'notes', 'Ghi chú lệch dòng.'),
        ('inventoryauditlines', 'variance_applied_at', 'TIMESTAMPTZ đã áp dụng điều chỉnh tồn; NULL = chưa áp dụng.'),
        ('inventoryauditlines', 'created_at', 'Tạo dòng kiểm.'),
        ('inventoryauditlines', 'updated_at', 'Cập nhật đếm.'),
        ('inventory_audit_session_events', 'id', 'PK sự kiện timeline.'),
        ('inventory_audit_session_events', 'session_id', 'FK inventoryauditsessions.id CASCADE.'),
        ('inventory_audit_session_events', 'event_type', 'Loại sự kiện (Created, Completed, Cancelled…).'),
        ('inventory_audit_session_events', 'payload', 'JSONB chi tiết sự kiện.'),
        ('inventory_audit_session_events', 'created_by', 'FK users.id RESTRICT.'),
        ('inventory_audit_session_events', 'created_at', 'Thời điểm sự kiện.'),

        -- refresh_tokens
        ('refresh_tokens', 'id', 'PK refresh token.'),
        ('refresh_tokens', 'user_id', 'FK users.id CASCADE.'),
        ('refresh_tokens', 'token', 'Refresh token (hash/UUID) — không log plain text.'),
        ('refresh_tokens', 'expires_at', 'Hết hạn phiên refresh.'),
        ('refresh_tokens', 'created_at', 'Cấp token.'),
        ('refresh_tokens', 'delete_ymd', 'Ngày thu hồi soft-delete (V4); NULL = còn hiệu lực.'),

        -- vouchers / redemptions
        ('vouchers', 'id', 'PK voucher.'),
        ('vouchers', 'code', 'Mã quét duy nhất (vd. DISCOUNT10).'),
        ('vouchers', 'name', 'Tên hiển thị khuyến mãi.'),
        ('vouchers', 'discount_type', 'CHECK: Percent | FixedAmount.'),
        ('vouchers', 'discount_value', 'Giá trị giảm (% hoặc tiền tùy discount_type).'),
        ('vouchers', 'is_active', 'BOOLEAN còn dùng được.'),
        ('vouchers', 'valid_from', 'Ngày bắt đầu hiệu lực (DATE, nullable).'),
        ('vouchers', 'valid_to', 'Ngày hết hiệu lực.'),
        ('vouchers', 'created_at', 'Tạo mã.'),
        ('vouchers', 'updated_at', 'Sửa mã.'),
        ('vouchers', 'used_count', 'Số lần đã dùng (V24); so với max_uses.'),
        ('vouchers', 'max_uses', 'Giới hạn lượt; NULL = không giới hạn.'),
        ('voucher_redemptions', 'id', 'PK lượt dùng voucher.'),
        ('voucher_redemptions', 'voucher_id', 'FK vouchers.id CASCADE.'),
        ('voucher_redemptions', 'sales_order_id', 'FK salesorders.id CASCADE UNIQUE — một đơn một redemption.'),
        ('voucher_redemptions', 'created_at', 'Thời điểm áp dụng voucher trên đơn.'),

        -- stockdispatch_lines (V46 join hint)
        ('stockdispatch_lines', 'id', 'PK dòng xuất.'),
        ('stockdispatch_lines', 'dispatch_id',
         'FK stockdispatches.id (phiếu xuất). Không join salesorders.id — nối đơn: stockdispatches.order_id = salesorders.id rồi dispatch_id = stockdispatches.id.'),
        ('stockdispatch_lines', 'inventory_id', 'FK inventory.id — lô/vị trí bị trừ. Join products qua inventory.product_id.'),
        ('stockdispatch_lines', 'quantity', 'SL xuất (>0) theo base unit của lô inventory.'),
        ('stockdispatch_lines', 'unit_price_snapshot', 'Đơn giá snapshot NUMERIC khi lập từ đơn (V36); NULL nếu xuất tay.'),

        -- cash_funds
        ('cash_funds', 'id', 'PK quỹ. FK: cashtransactions.fund_id, financeledger.fund_id.'),
        ('cash_funds', 'code', 'Mã quỹ duy nhất.'),
        ('cash_funds', 'name', 'Tên hiển thị quỹ (tiền mặt, NH…).'),
        ('cash_funds', 'is_default', 'BOOLEAN quỹ mặc định khi tạo giao dịch mới.'),
        ('cash_funds', 'is_active', 'BOOLEAN quỹ đang dùng.'),
        ('cash_funds', 'created_at', 'Tạo quỹ.'),
        ('cash_funds', 'updated_at', 'Sửa quỹ.'),

        -- meta registry
        ('ai_table_description', 'id', 'PK registry bảng AI.'),
        ('ai_table_description', 'table_name', 'Tên bảng PostgreSQL lowercase duy nhất; FK parent của ai_column_description.'),
        ('ai_table_description', 'description', 'Mô tả nghiệp vụ bảng cho prompt (merge SchemaArtifact).'),
        ('ai_table_description', 'created_at', 'Tạo dòng registry.'),
        ('ai_table_description', 'updated_at', 'Cập nhật mô tả bảng (V47/V48).'),
        ('ai_column_description', 'id', 'PK registry cột AI.'),
        ('ai_column_description', 'table_name', 'FK ai_table_description.table_name CASCADE.'),
        ('ai_column_description', 'column_name', 'Tên cột lowercase khớp information_schema.'),
        ('ai_column_description', 'description', 'Mô tả nghiệp vụ cột cho text-to-SQL (file này làm giàu).'),
        ('ai_column_description', 'created_at', 'Tạo dòng registry cột.'),
        ('ai_column_description', 'updated_at', 'Cập nhật mô tả cột.')
) AS v(table_name, column_name, description)
WHERE c.table_name = v.table_name
  AND c.column_name = v.column_name;
